for %%* in (../.) do set SWC=%%~n*
ECHO ^<?xml version="1.0" encoding="UTF-8"?^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO ^<!-- DO NOT EDIT THIS FILE: Some changes can lead to a crash of Polyspace products --^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO ^<polyspace_project name="Polyspace" language="C" author="czgng4" version="1.0" date="24/11/2014" path="file:/C:/Component/%SWC%/tools/Polyspace/Polyspace.bf.psprj" source="Bug Finder" rev="1.4"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^<source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
for %%F in (../src/*.c) do ECHO     ^<file path="file:/C:/Component/%SWC%/src/%%F"/^>  >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^</source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^<include^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/ansi/" order="0"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/v800/" order="1"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR202A_MicroCtrlrSuprt_Impl/include/P1M/R7F701311/" order="2"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR200A_ArSuprt_Impl/include/ASR4.0.3/" order="3"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR200A_ArSuprt_Impl/tools/contract/" order="4"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR201A_ArCplrSuprt_Impl/include/ASR4.0.3/" order="5"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR201A_ArCplrSuprt_Impl/tools/contract/" order="6"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR100A_NxtrMath_Impl/include/" order="7"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR101A_NxtrIntrpn_Impl/include/" order="8"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR104A_NxtrFil_Impl/include/" order="9"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR102A_NxtrTi_Impl/include/" order="10"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR103A_NxtrFixdPt_Impl/include/" order="11"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR998A_NxtrDet_Impl/include/" order="12"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/AR999A_ArchGlbPrm_Impl/include/" order="13"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/ES999A_ElecGlbPrm_Impl/include/" order="14"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/SF999A_SysGlbPrm_Impl/include/" order="15"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/%SWC%/include/" order="16"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<file path="file:/C:/Component/%SWC%/tools/contract/" order="17"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^</include^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^<module name="Polyspace" path="file:/C:/Component/%SWC%/tools/Polyspace/" isactive="true"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
for %%F in (../src/*.c) do ECHO       ^<file path="file:/C:/Component/%SWC%/src/%%F"/^>  >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^</source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<optionset name="Polyspace" isactive="true"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="*_checkers_preset"^>all^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="*_misra2"^>true^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="*_other"^>^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="*_report-generation"^>true^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="-bug-finder"^>true^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="-includes-to-ignore"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/ansi/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/v800/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR202A_MicroCtrlrSuprt_Impl/include/P1M/R7F701311/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR200A_ArSuprt_Impl/include/ASR4.0.3/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR200A_ArSuprt_Impl/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR201A_ArCplrSuprt_Impl/include/ASR4.0.3/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR201A_ArCplrSuprt_Impl/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR100A_NxtrMath_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR101A_NxtrIntrpn_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR104A_NxtrFil_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR102A_NxtrTi_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR103A_NxtrFixdPt_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR998A_NxtrDet_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/AR999A_ArchGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/ES999A_ElecGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/SF999A_SysGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO         ^<element^>file:/C:/Component/%SWC%/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="-misra2"^>all-rules^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="-post-analysis-command"^>^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<option flagname="-target"^>RH850^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^</optionset^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<result^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO       ^<file path="file:/C:/Component/%SWC%/doc/Polyspace_Results/BugFinder/" isactive="true"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^</result^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^</module^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^<target name="RH850" language="C"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-align"^>32^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-default-sign-of-char"^>signed^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-double-is-64bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-int-is-32bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-little-endian"^>Little^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-long-long-is-64bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO     ^<option flagname="-pointer-is-32bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO   ^</target^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
ECHO ^</polyspace_project^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.bf.psprj 
 
 
ECHO ^<?xml version="1.0" encoding="UTF-8"?^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO ^<!-- DO NOT EDIT THIS FILE: Some changes can lead to a crash of Polyspace products --^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO ^<polyspace_project name="Polyspace" language="C" author="czgng4" version="1.0" date="24/11/2014" path="file:/C:/Component/%SWC%/tools/Polyspace/Polyspace.psprj" source="Code Prover" rev="1.4"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^<source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
for %%F in (../src/*.c) do ECHO     ^<file path="file:/C:/Component/%SWC%/src/%%F"/^>  >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^</source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^<include^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/ansi/" order="0"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/v800/" order="1"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR202A_MicroCtrlrSuprt_Impl/include/P1M/R7F701311/" order="2"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR200A_ArSuprt_Impl/include/ASR4.0.3/" order="3"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR200A_ArSuprt_Impl/tools/contract/" order="4"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR201A_ArCplrSuprt_Impl/include/ASR4.0.3/" order="5"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR201A_ArCplrSuprt_Impl/tools/contract/" order="6"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR100A_NxtrMath_Impl/include/" order="7"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR101A_NxtrIntrpn_Impl/include/" order="8"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR104A_NxtrFil_Impl/include/" order="9"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR102A_NxtrTi_Impl/include/" order="10"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR103A_NxtrFixdPt_Impl/include/" order="11"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR998A_NxtrDet_Impl/include/" order="12"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/AR999A_ArchGlbPrm_Impl/include/" order="13"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/ES999A_ElecGlbPrm_Impl/include/" order="14"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/SF999A_SysGlbPrm_Impl/include/" order="15"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/%SWC%/include/" order="16"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<file path="file:/C:/Component/%SWC%/tools/contract/" order="17"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^</include^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^<module name="Polyspace" path="file:/C:/Component/%SWC%/tools/Polyspace/" isactive="true"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
for %%F in (../src/*.c) do ECHO       ^<file path="file:/C:/Component/%SWC%/src/%%F"/^>  >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^</source^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<optionset name="Polyspace" isactive="true"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="*_checkers_preset"^>all^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="*_misra2"^>true^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="*_other"^>^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="*_report-generation"^>true^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="-I"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/ansi/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/v800/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR202A_MicroCtrlrSuprt_Impl/include/P1M/R7F701311/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR200A_ArSuprt_Impl/include/ASR4.0.3/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR200A_ArSuprt_Impl/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR201A_ArCplrSuprt_Impl/include/ASR4.0.3/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR201A_ArCplrSuprt_Impl/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR100A_NxtrMath_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR101A_NxtrIntrpn_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR104A_NxtrFil_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR102A_NxtrTi_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR103A_NxtrFixdPt_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR998A_NxtrDet_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR999A_ArchGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/ES999A_ElecGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/SF999A_SysGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/%SWC%/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/%SWC%/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="-includes-to-ignore"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/ansi/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/TL103A_CplrSuprt/include/2015.1.5/v800/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR202A_MicroCtrlrSuprt_Impl/include/P1M/R7F701311/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR200A_ArSuprt_Impl/include/ASR4.0.3/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR200A_ArSuprt_Impl/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR201A_ArCplrSuprt_Impl/include/ASR4.0.3/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR201A_ArCplrSuprt_Impl/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR100A_NxtrMath_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR101A_NxtrIntrpn_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR104A_NxtrFil_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR102A_NxtrTi_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR103A_NxtrFixdPt_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR998A_NxtrDet_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/AR999A_ArchGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/ES999A_ElecGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/SF999A_SysGlbPrm_Impl/include/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO         ^<element^>file:/C:/Component/%SWC%/tools/contract/^</element^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="-main-generator-writes-variables"^>none^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="-misra2"^>all-rules^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="-post-analysis-command"^>^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<option flagname="-target"^>RH850^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^</optionset^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<result^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO       ^<file path="file:/C:/Component/%SWC%/doc/Polyspace_Results/CodeProver/" isactive="true"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^</result^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^</module^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^<target name="RH850" language="C"^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-align"^>32^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-default-sign-of-char"^>signed^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-double-is-64bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-int-is-32bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-little-endian"^>Little^</option^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-long-long-is-64bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO     ^<option flagname="-pointer-is-32bits"/^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO   ^</target^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
ECHO ^</polyspace_project^> >> C:\Component\%SWC%\tools\Polyspace\Polyspace.psprj 
