## ********************************************************************************************************************
## * Copyright 2016 Nxtr
## * Nxtr Confidential
## *
## * Module File Name:   Polyspace.bf.psprj.tpl
## * Module Description: Template for Polyspace project file.  To be processed by the mako template engine.
## * Project:            CBD
## * Author:             Owen Tosh
## ********************************************************************************************************************
## * Version Control:
## *-----------------------------------------------------------------------------------------------------------------
## * Date      Rev      Author    Change Description                                                       SCR #
## * --------  -------  --------  -----------------------------------------------------------------------  ---------
## * 10/04/16   1       OT        Initial version                                                          EA4#632
## ********************************************************************************************************************
##
##  Expected template variables:
##      program_name - string
##      options - dictionary:
##          include_paths - list of strings
##          source_files - list of strings
##          c_include_directory - list of strings
##          predefines - list of strings
##          ignored_files - list of strings
##          all_misra - boolean
##
<?xml version="1.0" encoding="UTF-8"?>
<!-- DO NOT EDIT THIS FILE: Some changes can lead to a crash of Polyspace products -->
<polyspace_project name="${program_name}" language="C" author="Nxtr" version="1.0" date="02/09/2016" path="file:/./Polyspace.bf.psprj" source="Bug Finder" rev="1.4">
  <source>
% for source_file in options['source_files']:
    <file path="file:/C:/./${source_file}"/>
% endfor
  </source>
  <include><% index = 0 %>
% for c_include_directory in options['c_include_directory']:
    <file path="file:/${c_include_directory}" order="${index}"/><% index += 1 %>
% endfor
% for include_path in options['include_paths']:
    <file path="file:/C:/./${include_path}" order="${index}"/><% index += 1 %>
% endfor
  </include>
  <module name="Polyspace" path="file:/./" isactive="true">
    <source>
    </source>
    <optionset name="${program_name}" isactive="true">
      <option flagname="*_checkers_preset">all</option>
      <option flagname="*_misra2">true</option>
      <option flagname="*_other">-include-headers-once ../../include/MemMap.h</option>
      <option flagname="-D">
        <element>__interrupt=</element>
        <element>__ghs_c_int__=int</element>
        <element>__CORE_V850E3V5__</element>
% for predefine in options['predefines']:
        <element>${predefine}</element>
% endfor
      </option>
      <option flagname="-allowed-pragmas">
        <element>ghs interrupt</element>
        <element>ghs section</element>
      </option>
      <option flagname="-bug-finder">true</option>
      <option flagname="-div-round-down">true</option>
      <option flagname="-includes-to-ignore">
% for ignored_file in options['ignored_files']:
<%
    if ignored_file.startswith('C:/'):
        prefix = ''
    else:
        prefix = 'C:/./'
%>        <element>file:/${prefix}${ignored_file}</element>
% endfor
      </option>
% if options['all_misra']:
      <option flagname="-misra2">all-rules</option>
% else:
      <option flagname="-misra2">
        <element>file:/C:/./MISRASettings.cfg</element>
      </option>
% endif
      <option flagname="-target">RH850</option>
    </optionset>
    <result>
      <file path="file:/C:/./~results/" isactive="true"/>
    </result>
  </module>
  <target name="RH850" language="C">
    <option flagname="-align">32</option>
    <option flagname="-default-sign-of-char">signed</option>
    <option flagname="-double-is-64bits"/>
    <option flagname="-int-is-32bits"/>
    <option flagname="-little-endian">Little</option>
    <option flagname="-long-long-is-64bits"/>
    <option flagname="-pointer-is-32bits"/>
  </target>
</polyspace_project>
