/* Header file for contract folder of CM700A */

#ifndef ELECGLBPRM_H	/* Multiple include preventer */
#define ELECGLBPRM_H

#define ELECGLBPRM_HWTQOFFS_HWNWTMTR_F32			10.0F
#define ELECGLBPRM_HWTQSATNLOWRLIM_HWNWTMTR_F32		(-10.0F)
#define ELECGLBPRM_HWTQSATNUPPRLIM_HWNWTMTR_F32		10.0F
#define ELECGLBPRM_HWTQSCA_ULS_F32					0.004884005F
#define ELECGLBPRM_NOFLT_CNT_U08					0U
#define ELECGLBPRM_OFFSTRIMNOTPRFMD_CNT_U08			1U
#define ELECGLBPRM_PRTCLFLT_CNT_U08					1U
#define ELECGLBPRM_SNSRINTFLT_CNT_U08  				2U

#endif
