
#ifndef ELECGLBPRM_H   /* Multiple include preventer */
#define ELECGLBPRM_H


#define ELECGLBPRM_STRTUPSTMTRDRVRININSTRT_CNT_U08	 		80U
#define ELECGLBPRM_GATEDRVCFGSTPRMBITSTRTGIDX_CNT_U08  		127U
#define ELECGLBPRM_GATEDRVCFGST_CNT_U08  					2U
#define ELECGLBPRM_GATEDRVOFFSTCHKREGWR1COL_CNT_U08  		0U
#define ELECGLBPRM_GATEDRVOFFSTCHKREGWR2COL_CNT_U08  		1U
#define ELECGLBPRM_GATEDRVOFFSTCHKDIGPINVRFYCOL_CNT_U08  	2U
#define ELECGLBPRM_GATEDRVOFFSTCHKSTSREGCOL_CNT_U08  		3U
#define ELECGLBPRM_GATEDRVOFFSTCHKDIAG1REGCOL_CNT_U08  		4U
#define ELECGLBPRM_GATEDRVOFFSTCHKDIAG2REGCOL_CNT_U08  		5U
#define ELECGLBPRM_GATEDRVOFFSTCHKVRFYRES0COL_CNT_U08  		6U
#define ELECGLBPRM_GATEDRVOFFSTCHKVRFYRES1COL_CNT_U08  		7U
#define ELECGLBPRM_GATEDRVOFFSTCHKSIZE_CNT_U08 				19U
#define ELECGLBPRM_GATEDRVOFFSTVRFYST_CNT_U08  				1U
#define ELECGLBPRM_GATEDRVOPERFLTMONRST_CNT_U08  			3U

extern const uint16 ELECGLBPRM_GATEDRVOFFSTCHKDATA_CNT_U16[20][8];


#endif
