/*===========================================================================*/
/* Module      = dr7f701311_irq.h                                            */
/* Version     = E1.00f                                                      */
/*               extracted from device file dr7f701311.dvf                   */
/*               generated by DeFiXRH850 0.7.5.2                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2014 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701311                                    */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701311_IRQ_H
#define __R7F701311_IRQ_H

#define IRQ_TABLE_START                 0x00000200u

#define RESET_ENABLE                    0x00000001u

// #define SYSERR_ENABLE                   0x00000010u

// #define HVTRAP_ENABLE                   0x00000020u

// #define FETRAPEX_ENABLE                 0x00000030u

// #define EITRAP0_ENABLE                  0x00000040u

// #define EITRAP1_ENABLE                  0x00000050u

// #define RIEX_ENABLE                     0x00000060u

// #define UCPOP_ENABLE                    0x00000080u

// #define MIP_MDP_ENABLE                  0x00000090u

// #define PIEX_ENABLE                     0x000000A0u

// #define MAEX_ENABLE                     0x000000C0u

// #define FENMI_ENABLE                    0x000000E0u

// #define FEINT_ENABLE                    0x000000F0u

// #define EINTPRIO_0_ENABLE               0x00000100u

// #define EINTPRIO_1_ENABLE               0x00000110u

// #define EINTPRIO_2_ENABLE               0x00000120u

// #define EINTPRIO_3_ENABLE               0x00000130u

// #define EINTPRIO_4_ENABLE               0x00000140u

// #define EINTPRIO_5_ENABLE               0x00000150u

// #define EINTPRIO_6_ENABLE               0x00000160u

// #define EINTPRIO_7_ENABLE               0x00000170u

// #define EINTPRIO_8_ENABLE               0x00000180u

// #define EINTPRIO_9_ENABLE               0x00000190u

// #define EINTPRIO_10_ENABLE              0x000001A0u

// #define EINTPRIO_11_ENABLE              0x000001B0u

// #define EINTPRIO_12_ENABLE              0x000001C0u

// #define EINTPRIO_13_ENABLE              0x000001D0u

// #define EINTPRIO_14_ENABLE              0x000001E0u

// #define EINTPRIO_15_ENABLE              0x000001F0u

 
// #define INTECM_ENABLE                   (IRQ_TABLE_START + 0x00000020u)

// #define INTWDTA0_ENABLE                 (IRQ_TABLE_START + 0x00000024u)

// #define INTDMA0_ENABLE                  (IRQ_TABLE_START + 0x00000040u)

// #define INTDMA1_ENABLE                  (IRQ_TABLE_START + 0x00000044u)

// #define INTDMA2_ENABLE                  (IRQ_TABLE_START + 0x00000048u)

// #define INTDMA3_ENABLE                  (IRQ_TABLE_START + 0x0000004Cu)

// #define INTDMA4_ENABLE                  (IRQ_TABLE_START + 0x00000050u)

// #define INTDMA5_ENABLE                  (IRQ_TABLE_START + 0x00000054u)

// #define INTDMA6_ENABLE                  (IRQ_TABLE_START + 0x00000058u)

// #define INTDMA7_ENABLE                  (IRQ_TABLE_START + 0x0000005Cu)

// #define INTDMA8_ENABLE                  (IRQ_TABLE_START + 0x00000060u)

// #define INTDMA9_ENABLE                  (IRQ_TABLE_START + 0x00000064u)

// #define INTDMA10_ENABLE                 (IRQ_TABLE_START + 0x00000068u)

// #define INTDMA11_ENABLE                 (IRQ_TABLE_START + 0x0000006Cu)

// #define INTDMA12_ENABLE                 (IRQ_TABLE_START + 0x00000070u)

// #define INTDMA13_ENABLE                 (IRQ_TABLE_START + 0x00000074u)

// #define INTDMA14_ENABLE                 (IRQ_TABLE_START + 0x00000078u)

// #define INTDMA15_ENABLE                 (IRQ_TABLE_START + 0x0000007Cu)

// #define INTP0_ENABLE                    (IRQ_TABLE_START + 0x00000080u)

// #define INTP1_ENABLE                    (IRQ_TABLE_START + 0x00000084u)

// #define INTP2_ENABLE                    (IRQ_TABLE_START + 0x00000088u)

// #define INTP3_ENABLE                    (IRQ_TABLE_START + 0x0000008Cu)

// #define INTP4_ENABLE                    (IRQ_TABLE_START + 0x00000090u)

// #define INTTSG30I0_ENABLE               (IRQ_TABLE_START + 0x000000A0u)

// #define INTTSG30I1_ENABLE               (IRQ_TABLE_START + 0x000000A4u)

// #define INTTSG30I2_ENABLE               (IRQ_TABLE_START + 0x000000A8u)

// #define INTTSG30I3_ENABLE               (IRQ_TABLE_START + 0x000000ACu)

// #define INTTSG30I4_ENABLE               (IRQ_TABLE_START + 0x000000B0u)

// #define INTTSG30I5_ENABLE               (IRQ_TABLE_START + 0x000000B4u)

// #define INTTSG30I6_ENABLE               (IRQ_TABLE_START + 0x000000B8u)

// #define INTTSG30I7_ENABLE               (IRQ_TABLE_START + 0x000000BCu)

// #define INTTSG30I8_ENABLE               (IRQ_TABLE_START + 0x000000C0u)

// #define INTTSG30I9_ENABLE               (IRQ_TABLE_START + 0x000000C4u)

// #define INTTSG30I10_ENABLE              (IRQ_TABLE_START + 0x000000C8u)

// #define INTTSG30I11_ENABLE              (IRQ_TABLE_START + 0x000000CCu)

// #define INTTSG30I12_ENABLE              (IRQ_TABLE_START + 0x000000D0u)

// #define INTTSG30IPEK_ENABLE             (IRQ_TABLE_START + 0x000000D4u)

// #define INTTSG30IVLY_ENABLE             (IRQ_TABLE_START + 0x000000D8u)

// #define INTTSG30IER_ENABLE              (IRQ_TABLE_START + 0x000000DCu)

// #define INTTSG30IWN_ENABLE              (IRQ_TABLE_START + 0x000000E0u)

// #define INTTSG31I0_ENABLE               (IRQ_TABLE_START + 0x000000E4u)

// #define INTTSG31I1_ENABLE               (IRQ_TABLE_START + 0x000000E8u)

// #define INTTSG31I2_ENABLE               (IRQ_TABLE_START + 0x000000ECu)

// #define INTTSG31I3_ENABLE               (IRQ_TABLE_START + 0x000000F0u)

// #define INTTSG31I4_ENABLE               (IRQ_TABLE_START + 0x000000F4u)

// #define INTTSG31I5_ENABLE               (IRQ_TABLE_START + 0x000000F8u)

// #define INTTSG31I6_ENABLE               (IRQ_TABLE_START + 0x000000FCu)

// #define INTTSG31I7_ENABLE               (IRQ_TABLE_START + 0x00000100u)

// #define INTTSG31I8_ENABLE               (IRQ_TABLE_START + 0x00000104u)

// #define INTTSG31I9_ENABLE               (IRQ_TABLE_START + 0x00000108u)

// #define INTTSG31I10_ENABLE              (IRQ_TABLE_START + 0x0000010Cu)

// #define INTTSG31I11_ENABLE              (IRQ_TABLE_START + 0x00000110u)

// #define INTTSG31I12_ENABLE              (IRQ_TABLE_START + 0x00000114u)

// #define INTTSG31IPEK_ENABLE             (IRQ_TABLE_START + 0x00000118u)

// #define INTTSG31IVLY_ENABLE             (IRQ_TABLE_START + 0x0000011Cu)

// #define INTTSG31IER_ENABLE              (IRQ_TABLE_START + 0x00000120u)

// #define INTTSG31IWN_ENABLE              (IRQ_TABLE_START + 0x00000124u)

// #define INTOSTM0_ENABLE                 (IRQ_TABLE_START + 0x00000128u)

// #define INTOSTM1_ENABLE                 (IRQ_TABLE_START + 0x0000012Cu)

// #define INTADCD0ERR_ENABLE              (IRQ_TABLE_START + 0x00000130u)

// #define INTADCD0I0_ENABLE               (IRQ_TABLE_START + 0x00000134u)

// #define INTADCD0I1_ENABLE               (IRQ_TABLE_START + 0x00000138u)

// #define INTADCD0I2_ENABLE               (IRQ_TABLE_START + 0x0000013Cu)

// #define INTADCD0I3_ENABLE               (IRQ_TABLE_START + 0x00000140u)

// #define INTADCD0I4_ENABLE               (IRQ_TABLE_START + 0x00000144u)

// #define INTCSIH0IRE_ENABLE              (IRQ_TABLE_START + 0x00000148u)

// #define INTCSIH0IR0S_ENABLE             (IRQ_TABLE_START + 0x0000014Cu)

// #define INTCSIH0IC0S_ENABLE             (IRQ_TABLE_START + 0x00000150u)

// #define INTCSIH0IR1_ENABLE              (IRQ_TABLE_START + 0x00000154u)

// #define INTCSIH0IC1_ENABLE              (IRQ_TABLE_START + 0x00000158u)

// #define INTCSIH0IR2_ENABLE              (IRQ_TABLE_START + 0x0000015Cu)

// #define INTCSIH0IC2_ENABLE              (IRQ_TABLE_START + 0x00000160u)

// #define INTCSIH0IJC_ENABLE              (IRQ_TABLE_START + 0x00000164u)

// #define INTCSIH1IRE_ENABLE              (IRQ_TABLE_START + 0x00000168u)

// #define INTCSIH1IR0S_ENABLE             (IRQ_TABLE_START + 0x0000016Cu)

// #define INTCSIH1IC0S_ENABLE             (IRQ_TABLE_START + 0x00000170u)

// #define INTCSIH1IR1_ENABLE              (IRQ_TABLE_START + 0x00000174u)

// #define INTCSIH1IC1_ENABLE              (IRQ_TABLE_START + 0x00000178u)

// #define INTCSIH1IR2_ENABLE              (IRQ_TABLE_START + 0x0000017Cu)

// #define INTCSIH1IC2_ENABLE              (IRQ_TABLE_START + 0x00000180u)

// #define INTCSIH1JC_ENABLE               (IRQ_TABLE_START + 0x00000184u)

// #define INTCSIH2IRE_ENABLE              (IRQ_TABLE_START + 0x00000188u)

// #define INTCSIH2IR_ENABLE               (IRQ_TABLE_START + 0x0000018Cu)

// #define INTCSIH2IC_ENABLE               (IRQ_TABLE_START + 0x00000190u)

// #define INTCSIH2IJC_ENABLE              (IRQ_TABLE_START + 0x00000194u)

// #define INTCSIH3IRE_ENABLE              (IRQ_TABLE_START + 0x00000198u)

// #define INTCSIH3IR_ENABLE               (IRQ_TABLE_START + 0x0000019Cu)

// #define INTCSIH3IC_ENABLE               (IRQ_TABLE_START + 0x000001A0u)

// #define INTCSIH3IJC_ENABLE              (IRQ_TABLE_START + 0x000001A4u)

// #define INTSCI30ERI_ENABLE              (IRQ_TABLE_START + 0x000001A8u)

// #define INTSCI30RXI_ENABLE              (IRQ_TABLE_START + 0x000001ACu)

// #define INTSCI30TXI_ENABLE              (IRQ_TABLE_START + 0x000001B0u)

// #define INTSCI30TEI_ENABLE              (IRQ_TABLE_START + 0x000001B4u)

// #define INTSCI31ERI_ENABLE              (IRQ_TABLE_START + 0x000001B8u)

// #define INTSCI31RXI_ENABLE              (IRQ_TABLE_START + 0x000001BCu)

// #define INTSCI31TXI_ENABLE              (IRQ_TABLE_START + 0x000001C0u)

// #define INTSCI31TEI_ENABLE              (IRQ_TABLE_START + 0x000001C4u)

// #define INTRLIN30UR2_ENABLE             (IRQ_TABLE_START + 0x000001C8u)

// #define INTRLIN30UR1_ENABLE             (IRQ_TABLE_START + 0x000001CCu)

// #define INTRLIN30UR0_ENABLE             (IRQ_TABLE_START + 0x000001D0u)

// #define INTRLIN31UR2_ENABLE             (IRQ_TABLE_START + 0x000001D4u)

// #define INTRLIN31UR1_ENABLE             (IRQ_TABLE_START + 0x000001D8u)

// #define INTRLIN31UR0_ENABLE             (IRQ_TABLE_START + 0x000001DCu)

// #define INTSINT3_ENABLE                 (IRQ_TABLE_START + 0x000001E0u)

// #define INTSINT4_ENABLE                 (IRQ_TABLE_START + 0x000001E4u)

// #define INTP5_ENABLE                    (IRQ_TABLE_START + 0x00000200u)

// #define INTP6_ENABLE                    (IRQ_TABLE_START + 0x00000204u)

// #define INTP7_ENABLE                    (IRQ_TABLE_START + 0x00000208u)

// #define INTP8_ENABLE                    (IRQ_TABLE_START + 0x0000020Cu)

// #define INTP9_ENABLE                    (IRQ_TABLE_START + 0x00000210u)

// #define INTTAUJ0I0_ENABLE               (IRQ_TABLE_START + 0x00000214u)

// #define INTTAUJ0I1_ENABLE               (IRQ_TABLE_START + 0x00000218u)

// #define INTTAUJ0I2_ENABLE               (IRQ_TABLE_START + 0x0000021Cu)

// #define INTTAUJ0I3_ENABLE               (IRQ_TABLE_START + 0x00000220u)

// #define INTTAUJ1I0_ENABLE               (IRQ_TABLE_START + 0x00000224u)

// #define INTTAUJ1I1_ENABLE               (IRQ_TABLE_START + 0x00000228u)

// #define INTTAUJ1I2_ENABLE               (IRQ_TABLE_START + 0x0000022Cu)

// #define INTTAUJ1I3_ENABLE               (IRQ_TABLE_START + 0x00000230u)

// #define INTTAUD0I0_ENABLE               (IRQ_TABLE_START + 0x00000234u)

// #define INTTAUD0I1_ENABLE               (IRQ_TABLE_START + 0x00000238u)

// #define INTTAUD0I2_ENABLE               (IRQ_TABLE_START + 0x0000023Cu)

// #define INTTAUD0I3_ENABLE               (IRQ_TABLE_START + 0x00000240u)

// #define INTTAUD0I4_ENABLE               (IRQ_TABLE_START + 0x00000244u)

// #define INTTAUD0I5_ENABLE               (IRQ_TABLE_START + 0x00000248u)

// #define INTTAUD0I6_ENABLE               (IRQ_TABLE_START + 0x0000024Cu)

// #define INTTAUD0I7_ENABLE               (IRQ_TABLE_START + 0x00000250u)

// #define INTTAUD0I8_ENABLE               (IRQ_TABLE_START + 0x00000254u)

// #define INTTAUD0I9_ENABLE               (IRQ_TABLE_START + 0x00000258u)

// #define INTTAUD0I10_ENABLE              (IRQ_TABLE_START + 0x0000025Cu)

// #define INTTAUD0I11_ENABLE              (IRQ_TABLE_START + 0x00000260u)

// #define INTTAUD0I12_ENABLE              (IRQ_TABLE_START + 0x00000264u)

// #define INTTAUD0I13_ENABLE              (IRQ_TABLE_START + 0x00000268u)

// #define INTTAUD0I14_ENABLE              (IRQ_TABLE_START + 0x0000026Cu)

// #define INTTAUD0I15_ENABLE              (IRQ_TABLE_START + 0x00000270u)

// #define INTTAUD1I0_ENABLE               (IRQ_TABLE_START + 0x00000278u)

// #define INTTAUD1I1_ENABLE               (IRQ_TABLE_START + 0x0000027Cu)

// #define INTTAUD1I2_ENABLE               (IRQ_TABLE_START + 0x00000280u)

// #define INTTAUD1I3_ENABLE               (IRQ_TABLE_START + 0x00000284u)

// #define INTTAUD1I4_ENABLE               (IRQ_TABLE_START + 0x00000288u)

// #define INTTAUD1I5_ENABLE               (IRQ_TABLE_START + 0x0000028Cu)

// #define INTTAUD1I6_ENABLE               (IRQ_TABLE_START + 0x00000290u)

// #define INTTAUD1I7_ENABLE               (IRQ_TABLE_START + 0x00000294u)

// #define INTTAUD1I8_ENABLE               (IRQ_TABLE_START + 0x00000298u)

// #define INTTAUD1I9_ENABLE               (IRQ_TABLE_START + 0x0000029Cu)

// #define INTTAUD1I10_ENABLE              (IRQ_TABLE_START + 0x000002A0u)

// #define INTTAUD1I11_ENABLE              (IRQ_TABLE_START + 0x000002A4u)

// #define INTTAUD1I12_ENABLE              (IRQ_TABLE_START + 0x000002A8u)

// #define INTTAUD1I13_ENABLE              (IRQ_TABLE_START + 0x000002ACu)

// #define INTTAUD1I14_ENABLE              (IRQ_TABLE_START + 0x000002B0u)

// #define INTTAUD1I15_ENABLE              (IRQ_TABLE_START + 0x000002B4u)

// #define INTCSIG0IRE_ENABLE              (IRQ_TABLE_START + 0x000002B8u)

// #define INTCSIG0IC_ENABLE               (IRQ_TABLE_START + 0x000002BCu)

// #define INTCSIG0IR_ENABLE               (IRQ_TABLE_START + 0x000002C0u)

// #define INTADCD1ERR_ENABLE              (IRQ_TABLE_START + 0x000002C4u)

// #define INTADCD1I0_ENABLE               (IRQ_TABLE_START + 0x000002C8u)

// #define INTADCD1I1_ENABLE               (IRQ_TABLE_START + 0x000002CCu)

// #define INTADCD1I2_ENABLE               (IRQ_TABLE_START + 0x000002D0u)

// #define INTADCD1I3_ENABLE               (IRQ_TABLE_START + 0x000002D4u)

// #define INTADCD1I4_ENABLE               (IRQ_TABLE_START + 0x000002D8u)

// #define INTRCAN0ERR_ENABLE              (IRQ_TABLE_START + 0x000002DCu)

// #define INTRCAN0REC_ENABLE              (IRQ_TABLE_START + 0x000002E0u)

// #define INTRCAN0TRX_ENABLE              (IRQ_TABLE_START + 0x000002E4u)

// #define INTRCAN1ERR_ENABLE              (IRQ_TABLE_START + 0x000002E8u)

// #define INTRCAN1REC_ENABLE              (IRQ_TABLE_START + 0x000002ECu)

// #define INTRCAN1TRX_ENABLE              (IRQ_TABLE_START + 0x000002F0u)

// #define INTRCANGERR_ENABLE              (IRQ_TABLE_START + 0x000002F4u)

// #define INTRCANGRECC_ENABLE             (IRQ_TABLE_START + 0x000002F8u)

// #define INTFLX0LINE0_ENABLE             (IRQ_TABLE_START + 0x00000308u)

// #define INTFLX0LINE1_ENABLE             (IRQ_TABLE_START + 0x0000030Cu)

// #define INTFLX0TIM0_ENABLE              (IRQ_TABLE_START + 0x00000310u)

// #define INTFLX0TIM1_ENABLE              (IRQ_TABLE_START + 0x00000314u)

// #define INTFLX0TIM2_ENABLE              (IRQ_TABLE_START + 0x00000318u)

// #define INTFLX0FDA_ENABLE               (IRQ_TABLE_START + 0x0000031Cu)

// #define INTFLX0FW_ENABLE                (IRQ_TABLE_START + 0x00000320u)

// #define INTFLX0OW_ENABLE                (IRQ_TABLE_START + 0x00000324u)

// #define INTFLX0OT_ENABLE                (IRQ_TABLE_START + 0x00000328u)

// #define INTFLX0IQF_ENABLE               (IRQ_TABLE_START + 0x0000032Cu)

// #define INTFLX0IQE_ENABLE               (IRQ_TABLE_START + 0x00000330u)

// #define INTSCI32ERI_ENABLE              (IRQ_TABLE_START + 0x00000368u)

// #define INTSCI32RXI_ENABLE              (IRQ_TABLE_START + 0x0000036Cu)

// #define INTSCI32TXI_ENABLE              (IRQ_TABLE_START + 0x00000370u)

// #define INTSCI32TEI_ENABLE              (IRQ_TABLE_START + 0x00000374u)

// #define INTPSI50SI_ENABLE               (IRQ_TABLE_START + 0x00000388u)

// #define INTPSI50RI_ENABLE               (IRQ_TABLE_START + 0x0000038Cu)

// #define INTPSI50TI_ENABLE               (IRQ_TABLE_START + 0x00000390u)

// #define INTPSI51SI_ENABLE               (IRQ_TABLE_START + 0x00000394u)

// #define INTPSI51RI_ENABLE               (IRQ_TABLE_START + 0x00000398u)

// #define INTPSI51TI_ENABLE               (IRQ_TABLE_START + 0x0000039Cu)

// #define INTSENT0SI_ENABLE               (IRQ_TABLE_START + 0x000003A0u)

// #define INTSENT0RI_ENABLE               (IRQ_TABLE_START + 0x000003A4u)

// #define INTSENT1SI_ENABLE               (IRQ_TABLE_START + 0x000003A8u)

// #define INTSENT1RI_ENABLE               (IRQ_TABLE_START + 0x000003ACu)

// #define INTSENT2SI_ENABLE               (IRQ_TABLE_START + 0x000003B0u)

// #define INTSENT2RI_ENABLE               (IRQ_TABLE_START + 0x000003B4u)

// #define INTSENT3SI_ENABLE               (IRQ_TABLE_START + 0x000003B8u)

// #define INTSENT3RI_ENABLE               (IRQ_TABLE_START + 0x000003BCu)

// #define INTSENT4SI_ENABLE               (IRQ_TABLE_START + 0x000003C0u)

// #define INTSENT4RI_ENABLE               (IRQ_TABLE_START + 0x000003C4u)

// #define INTSENT5SI_ENABLE               (IRQ_TABLE_START + 0x000003C8u)

// #define INTSENT5RI_ENABLE               (IRQ_TABLE_START + 0x000003CCu)

// #define INTDTSTC0_ENABLE                (IRQ_TABLE_START + 0x000003D0u)

// #define INTDTSTC1_ENABLE                (IRQ_TABLE_START + 0x000003D4u)

// #define INTDTSTC2_ENABLE                (IRQ_TABLE_START + 0x000003D8u)

// #define INTDTSTC3_ENABLE                (IRQ_TABLE_START + 0x000003DCu)

// #define INTDTSCM0_ENABLE                (IRQ_TABLE_START + 0x000003E0u)

// #define INTDTSCM1_ENABLE                (IRQ_TABLE_START + 0x000003E4u)

// #define INTDTSCM2_ENABLE                (IRQ_TABLE_START + 0x000003E8u)

// #define INTDTSCM3_ENABLE                (IRQ_TABLE_START + 0x000003ECu)

// #define INTSINT0_ENABLE                 (IRQ_TABLE_START + 0x000003F0u)

// #define INTSINT1_ENABLE                 (IRQ_TABLE_START + 0x000003F4u)

// #define INTSINT2_ENABLE                 (IRQ_TABLE_START + 0x000003F8u)

// #define INTTAUJ2I0_ENABLE               (IRQ_TABLE_START + 0x00000400u)

// #define INTTAUJ2I1_ENABLE               (IRQ_TABLE_START + 0x00000404u)

// #define INTTAUJ2I2_ENABLE               (IRQ_TABLE_START + 0x00000408u)

// #define INTTAUJ2I3_ENABLE               (IRQ_TABLE_START + 0x0000040Cu)

// #define INTTAUD2I0_ENABLE               (IRQ_TABLE_START + 0x00000410u)

// #define INTTAUD2I1_ENABLE               (IRQ_TABLE_START + 0x00000414u)

// #define INTTAUD2I2_ENABLE               (IRQ_TABLE_START + 0x00000418u)

// #define INTTAUD2I3_ENABLE               (IRQ_TABLE_START + 0x0000041Cu)

// #define INTTAUD2I4_ENABLE               (IRQ_TABLE_START + 0x00000420u)

// #define INTTAUD2I5_ENABLE               (IRQ_TABLE_START + 0x00000424u)

// #define INTTAUD2I6_ENABLE               (IRQ_TABLE_START + 0x00000428u)

// #define INTTAUD2I7_ENABLE               (IRQ_TABLE_START + 0x0000042Cu)

// #define INTTAUD2I8_ENABLE               (IRQ_TABLE_START + 0x00000430u)

// #define INTTAUD2I9_ENABLE               (IRQ_TABLE_START + 0x00000434u)

// #define INTTAUD2I10_ENABLE              (IRQ_TABLE_START + 0x00000438u)

// #define INTTAUD2I11_ENABLE              (IRQ_TABLE_START + 0x0000043Cu)

// #define INTTAUD2I12_ENABLE              (IRQ_TABLE_START + 0x00000440u)

// #define INTTAUD2I13_ENABLE              (IRQ_TABLE_START + 0x00000444u)

// #define INTTAUD2I14_ENABLE              (IRQ_TABLE_START + 0x00000448u)

// #define INTTAUD2I15_ENABLE              (IRQ_TABLE_START + 0x0000044Cu)

// #define INTENCA0IOV_ENABLE              (IRQ_TABLE_START + 0x00000450u)

// #define INTENCA0I0_ENABLE               (IRQ_TABLE_START + 0x00000454u)

// #define INTENCA0I1_ENABLE               (IRQ_TABLE_START + 0x00000458u)

// #define INTENCA0IUD_ENABLE              (IRQ_TABLE_START + 0x0000045Cu)

// #define INTENCA0IEC_ENABLE              (IRQ_TABLE_START + 0x00000460u)

// #define INTENCA1IOV_ENABLE              (IRQ_TABLE_START + 0x00000464u)

// #define INTENCA1I0_ENABLE               (IRQ_TABLE_START + 0x00000468u)

// #define INTENCA1I1_ENABLE               (IRQ_TABLE_START + 0x0000046Cu)

// #define INTENCA1IUD_ENABLE              (IRQ_TABLE_START + 0x00000470u)

// #define INTENCA1IEC_ENABLE              (IRQ_TABLE_START + 0x00000474u)

// #define INTTPBA0IPRD_ENABLE             (IRQ_TABLE_START + 0x00000478u)

// #define INTTPBA0IDTY_ENABLE             (IRQ_TABLE_START + 0x0000047Cu)

// #define INTTPBA0IPAT_ENABLE             (IRQ_TABLE_START + 0x00000480u)

// #define INTTPBA1IPRD_ENABLE             (IRQ_TABLE_START + 0x00000484u)

// #define INTTPBA1IDTY_ENABLE             (IRQ_TABLE_START + 0x00000488u)

// #define INTTPBA1IPAT_ENABLE             (IRQ_TABLE_START + 0x0000048Cu)

// #define INTADCD0MPX_ENABLE              (IRQ_TABLE_START + 0x00000498u)

// #define INTADCD1MPX_ENABLE              (IRQ_TABLE_START + 0x0000049Cu)

// #define INTP10_ENABLE                   (IRQ_TABLE_START + 0x000004A0u)

// #define INTP11_ENABLE                   (IRQ_TABLE_START + 0x000004A4u)

// #define INTP12_ENABLE                   (IRQ_TABLE_START + 0x000004A8u)

// #define INTFLENDNM_ENABLE               (IRQ_TABLE_START + 0x000005ECu)

// #define INTFLERR_ENABLE                 (IRQ_TABLE_START + 0x000005FCu)



#endif /* __R7F701311_IRQ_H */
