
#ifndef FLTINJ_H
#define FLTINJ_H

#define FLTINJ_VEHSIGCDNG_SERLCOMVEHLATA		(14U)
#define FLTINJ_VEHSIGCDNG_SERLCOMVEHLGTA		(13U)
#define FLTINJ_VEHSIGCDNG_SERLCOMVEHSPD			(12U)
#define FLTINJ_VEHSIGCDNG_SERLCOMVEHYAWRATE		(10U)

#endif
