/* file: C:/Hari/Work/SynergyProjects/T1xx_Synergy/BuildPrep/07.01.05_Work/Z_Work_1_8917_ShortTerm/GM_T1XX_EPS_RH850/generate/osConfigBlock.c */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: C:/Users/nz2654/AppData/Local/Temp/DaVinci/Cfg-1345187/Generation/Cfg_Gen-1484071352018-0/OsProxyFiles-1484072167553-0/Os_ActiveEcuC.arxml */
/* Generation time: Tue Jan 10 13:16:12 2017 */
/* Unlimited license CBD1400351 for Nxtr Automotive, Project License, EPS */
/* Implementation: RH850_P1M */
/* Version of general code: 9.01.06 */
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osStacks.h"
#else
 #include <osStacks.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

#pragma ghs section rodata=".osConfigBlock_rodata"
#pragma ghs section rosdata=".osConfigBlock_rosdata"

/* MISRA RULE 8.10 VIOLATION: osConfigBlock is accessed by several modules in many configurations.
*  Declaring this variable static in the other cases would increase code complexity too much.
*/
osqROM0 osqROM1 const osqROM2 tsConfigBlock osqROM3 osConfigBlock = /* PRQA S 1504 */ 
{
   /* Frame */
   {0x82, 0x2A, 0x0C, 0xC4}, /* aucMagicNumber */
   (osuint16)(sizeof(osConfigBlock)), /* Length (little endian) */
   9,
   osdVrmMajRelNumRef,    /* MajorVersion */
   osdVrmMinRelNumRef,    /* MinorVersion */
   (osuint16)3,           /* ConfigBlockVersion */
   (osuint16)1, /* UserConfigVersion */
   /* cargo --------------------------------------------------------------- */
   &osConfigBlock,
   /* start addresses of sub-containers (fixed number) */
   &(osConfigBlock.uiNumberOfTasks),        /* Sub-Container 0 */
   (osConfigBlock.aulTaskStartAddress),     /* Sub-Container 1 */
   (osConfigBlock.aucTaskPreemptive),       /* Sub-Container 2 */
   (osConfigBlock.aucTaskTrusted),          /* Sub-Container 3 */
   (osConfigBlock.aulTaskStackStartAddress),/* Sub-Container 4 */
   (osConfigBlock.aulTaskStackEndAddress),  /* Sub-Container 5 */
   (osConfigBlock.acTaskToAppl),            /* Sub-Container 6 */
   (osConfigBlock.aucIsrTrusted),           /* Sub-Container 7 */
   (osConfigBlock.acIsrToAppl),             /* Sub-Container 8 */
   (osConfigBlock.applTrusted),             /* Sub-Container 9 */
   (osConfigBlock.trustedFunctions),        /* Sub-Container 10 */
   (osConfigBlock.nonTrustedFunctions),     /* Sub-Container 11 */
   (osConfigBlock.cat2IsrStartAddress),     /* Sub-Container 12 */
   (osConfigBlock.IsrNestable),             /* Sub-Container 13 */
   (osConfigBlock.ProcessToCore),           /* Sub-Container 14 */
   (osConfigBlock.AlarmToCore),             /* Sub-Container 15 */
   (osConfigBlock.ResourceToCore),          /* Sub-Container 16 */
   (osConfigBlock.CounterToCore),           /* Sub-Container 17 */
   (osConfigBlock.ScheduleTableToCore),     /* Sub-Container 18 */
   (osConfigBlock.ApplicationToCore),       /* Sub-Container 19 */
   (osConfigBlock.TrustedFunctionToCore),   /* Sub-Container 20 */
   (osConfigBlock.NonTrustedFunctionToCore),/* Sub-Container 21 */
   (osConfigBlock.CcbAddress),              /* Sub-Container 22 */
   (osConfigBlock.peripheralRegions),       /* Sub-Container 23 */
   (osConfigBlock.SpinlockLockMethods),     /* Sub-Container 24 */
   (osConfigBlock.SpinlockLockTypes),       /* Sub-Container 25 */
   (osConfigBlock.OptimizedSpinlockVars),   /* Sub-Container 26 */
   (osConfigBlock.osCat2IsrStacks),         /* Sub-Container 27 */
   (osConfigBlock.osIsrChannel),            /* Sub-Container 28 */
   (osConfigBlock.osIsrPrioLevel),          /* Sub-Container 29 */
   (osConfigBlock.osIsrToCore),             /* Sub-Container 30 */
   (osConfigBlock.applMPUConfig),           /* Sub-Container 31 */
   (osConfigBlock.osMPUConfig),             /* Sub-Container 32 */
   (osConfigBlock.applMpuASID),             /* Sub-Container 33 */
   /* Sub-Container 0 */
   osdNumberOfAllTasks,
   osdNumberOfCat2ISRs,
   osdNumberOfTrustedFunctions,
   osdNumberOfNonTrustedFunctions,
   osdNumberOfApplications,
   osdNumberOfPeripheralRegions,
   osdStackUsageMeasurement,
   osdNumberOfAlarms,
   osdNumberOfAllResources,
   osdNumberOfAvailableCores,
   osdNumberOfCounters,
   osdNumberOfProcesses,
   osdNumberOfScheduleTables,
   0,
   osdNumberOfCat1ISRs,
   osdNumberOfMpuRegions,
   osdNumberOfDynamicMpuRegions_c0,
   osdNumberOfStaticMpuRegions,

   {
      {(osStackPtrType)osdSystemStack_c0_BOT, (osStackPtrType)osdSystemStack_c0_TOP},
   },

   /* Sub-Container 1, task start addresses */
   {
      &osSystemExtendedTaskfunc,
      &Task_InitBsw_Appl10func,
      &Task_Init_Appl10func,
      &Task_Init_Appl6func,
      &Task_Shutdown_Appl0func,
      &Task_4msBsw_Appl10func,
      &Task_2msTmplMonr_Appl10func,
      &Task_2ms_Appl10func,
      &Task_2ms_Appl6func,
      &Task_4ms_Appl10func,
      &Task_10ms_Appl10func,
      &Task_10ms_Appl6func,
      &Task_10msBsw_Appl10func,
      &Task_100ms_Appl10func,
      &osSystemBasicTaskfunc,
      (osTaskFctType)0
   },
   /* Sub-Container 2, task preemptiveness */
   {
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypeNonPreempt,
      0
   },
   /* Sub-Container 3, task trusted */
   {
      1,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0
   },
   /* Sub-Container 4, stack start address */
   {
      (osStackPtrType)osdosSystemExtendedTask_BOT,
      (osStackPtrType)osdTask_InitBsw_Appl10_BOT,
      (osStackPtrType)osdTask_Init_Appl10_BOT,
      (osStackPtrType)osdTask_Init_Appl6_BOT,
      (osStackPtrType)osdTask_Shutdown_Appl0_BOT,
      (osStackPtrType)osdTask_4msBsw_Appl10_BOT,
      (osStackPtrType)osdTask_2msTmplMonr_Appl10_BOT,
      (osStackPtrType)osdTask_2ms_Appl10_BOT,
      (osStackPtrType)osdTask_2ms_Appl6_BOT,
      (osStackPtrType)osdTask_4ms_Appl10_BOT,
      (osStackPtrType)osdTask_10ms_Appl10_BOT,
      (osStackPtrType)osdTask_10ms_Appl6_BOT,
      (osStackPtrType)osdTask_10msBsw_Appl10_BOT,
      (osStackPtrType)osdTask_100ms_Appl10_BOT,
      (osStackPtrType)osdosSystemBasicTask_BOT,
      (osStackPtrType)0
   },
   /* Sub-Container 5, stack end addresses */
   {
      (osStackPtrType)osdosSystemExtendedTask_TOP,
      (osStackPtrType)osdTask_InitBsw_Appl10_TOP,
      (osStackPtrType)osdTask_Init_Appl10_TOP,
      (osStackPtrType)osdTask_Init_Appl6_TOP,
      (osStackPtrType)osdTask_Shutdown_Appl0_TOP,
      (osStackPtrType)osdTask_4msBsw_Appl10_TOP,
      (osStackPtrType)osdTask_2msTmplMonr_Appl10_TOP,
      (osStackPtrType)osdTask_2ms_Appl10_TOP,
      (osStackPtrType)osdTask_2ms_Appl6_TOP,
      (osStackPtrType)osdTask_4ms_Appl10_TOP,
      (osStackPtrType)osdTask_10ms_Appl10_TOP,
      (osStackPtrType)osdTask_10ms_Appl6_TOP,
      (osStackPtrType)osdTask_10msBsw_Appl10_TOP,
      (osStackPtrType)osdTask_100ms_Appl10_TOP,
      (osStackPtrType)osdosSystemBasicTask_TOP,
      (osStackPtrType)0
   },
   /* Sub-Container 6, translation table: task -> os-application */
   {
      osSystemApplicationCore0,   /* osSystemExtendedTask */
      Appl10,   /* Task_InitBsw_Appl10 */
      Appl10,   /* Task_Init_Appl10 */
      Appl6,   /* Task_Init_Appl6 */
      Appl0,   /* Task_Shutdown_Appl0 */
      Appl10,   /* Task_4msBsw_Appl10 */
      Appl10,   /* Task_2msTmplMonr_Appl10 */
      Appl10,   /* Task_2ms_Appl10 */
      Appl6,   /* Task_2ms_Appl6 */
      Appl10,   /* Task_4ms_Appl10 */
      Appl10,   /* Task_10ms_Appl10 */
      Appl6,   /* Task_10ms_Appl6 */
      Appl10,   /* Task_10msBsw_Appl10 */
      Appl10,   /* Task_100ms_Appl10 */
      osSystemApplicationCore0,   /* osSystemBasicTask */
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 7, isr trusted */
   {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0
   },
   /* Sub-Container 8, translation table: isr -> os-application */
   {
      Appl6,   /* CanIsrGlobalStatus*/
      Appl6,   /* CanIsrRxFifo*/
      Appl6,   /* CanIsrStatus_0*/
      Appl6,   /* CanIsrStatus_1*/
      Appl6,   /* CanIsrTx_0*/
      Appl6,   /* CanIsrTx_1*/
      Appl10,   /* MCU_ECM_EIC_CAT2_ISR*/
      Appl0,   /* SPI_CSIG0_TIC_CAT2_ISR*/
      Appl0,   /* SPI_CSIG0_TIRE_CAT2_ISR*/
      Appl0,   /* SPI_CSIG0_TIR_CAT2_ISR*/
      Appl0,   /* SPI_CSIH0_TIC_CAT2_ISR*/
      Appl0,   /* SPI_CSIH0_TIRE_CAT2_ISR*/
      Appl0,   /* SPI_CSIH0_TIR_CAT2_ISR*/
      Appl0,   /* SPI_CSIH2_TIC_CAT2_ISR*/
      Appl0,   /* SPI_CSIH2_TIRE_CAT2_ISR*/
      Appl0,   /* SPI_CSIH2_TIR_CAT2_ISR*/
      Appl10,   /* SnsrMeasStrtIrq*/
      osSystemApplicationCore0,   /* osOstmInterrupt_c0*/
      osSystemApplicationCore0,   /* osSystemCat2ISR*/
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 9, is application trusted information */
   {
      osdTRUE, /* Appl0 */
      osdFALSE, /* Appl10 */
      osdFALSE, /* Appl6 */
      osdTRUE, /* osSystemApplicationCore0 */
      0
   },
   /* Sub-Container 10, trusted functions */
   {
      {(TrustedFunctionType)&TRUSTED_Adc0OutpInin, 0},
      {(TrustedFunctionType)&TRUSTED_ApplXcpWrCmn, 0},
      {(TrustedFunctionType)&TRUSTED_CritRegInitChk, 0},
      {(TrustedFunctionType)&TRUSTED_CritRegPerChk, 0},
      {(TrustedFunctionType)&TRUSTED_DmaRegInin, 0},
      {(TrustedFunctionType)&TRUSTED_DtsClnUp, 0},
      {(TrustedFunctionType)&TRUSTED_DtsInin, 0},
      {(TrustedFunctionType)&TRUSTED_Fls_MainFunction, 0},
      {(TrustedFunctionType)&TRUSTED_GetResource, 0},
      {(TrustedFunctionType)&TRUSTED_IpgInin, 0},
      {(TrustedFunctionType)&TRUSTED_NvM_MainFunction, 0},
      {(TrustedFunctionType)&TRUSTED_NxtrWdgM_Init, 0},
      {(TrustedFunctionType)&TRUSTED_ReleaseResource, 0},
      {(TrustedFunctionType)&TRUSTED_Spi_AsyncTransmit, 0},
      {(TrustedFunctionType)&TRUSTED_osSystemTrustedFunction, 3},
      {0, 0}
   },
   /* Sub-Container 11, non trusted functions */
   {
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_BswM_RequestMode, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CanStop, 2},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CmnMfgSrv_CallSvc10, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CmnMfgSrv_Init, 2},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_ClrAllDiagc, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_ClrHwAgTrimVal, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_DemDcmDisableDTCSetting, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_DemDcmEnableDTCSetting, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_DiDtcRecUpd, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_EnaDtcRecUpd, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_GmFctDiReq, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_CustDiagc_UpdHwAgTrimVal, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_GMLANInit, 2},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_GmMsg778BusHiSpd_DtcStsChgd, 2},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_EraseNvBlock, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_GetDataIndex, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_GetErrorStatus, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_InvalidateNvBlock, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_ReadBlock, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_SetBlockProtection, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_SetDataIndex, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_SetRamBlockStatus, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_NvM_WriteBlock, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_Rte_Call_CopyCalPageReq_Oper, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_Rte_Call_SetCalPageReq_Oper, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_StHlthSigStc_ClrDataSample, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_StHlthSigStc_UpdDataSample, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_StHlthSigStc_UpdNvmPim, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_SyncCrc_GetAvlCrcHwUnit, 1},
      {(NonTrustedFunctionType)&NONTRUSTED_NtWrapS_SyncCrc_RelsCrcHwUnit, 1},
      {0, 0}
   },
   /* Sub-Container 12, Cat 2 ISR start addresses */
   {
      &CanIsrGlobalStatusfunc,   /* CanIsrGlobalStatus */
      &CanIsrRxFifofunc,   /* CanIsrRxFifo */
      &CanIsrStatus_0func,   /* CanIsrStatus_0 */
      &CanIsrStatus_1func,   /* CanIsrStatus_1 */
      &CanIsrTx_0func,   /* CanIsrTx_0 */
      &CanIsrTx_1func,   /* CanIsrTx_1 */
      &MCU_ECM_EIC_CAT2_ISRfunc,   /* MCU_ECM_EIC_CAT2_ISR */
      &SPI_CSIG0_TIC_CAT2_ISRfunc,   /* SPI_CSIG0_TIC_CAT2_ISR */
      &SPI_CSIG0_TIRE_CAT2_ISRfunc,   /* SPI_CSIG0_TIRE_CAT2_ISR */
      &SPI_CSIG0_TIR_CAT2_ISRfunc,   /* SPI_CSIG0_TIR_CAT2_ISR */
      &SPI_CSIH0_TIC_CAT2_ISRfunc,   /* SPI_CSIH0_TIC_CAT2_ISR */
      &SPI_CSIH0_TIRE_CAT2_ISRfunc,   /* SPI_CSIH0_TIRE_CAT2_ISR */
      &SPI_CSIH0_TIR_CAT2_ISRfunc,   /* SPI_CSIH0_TIR_CAT2_ISR */
      &SPI_CSIH2_TIC_CAT2_ISRfunc,   /* SPI_CSIH2_TIC_CAT2_ISR */
      &SPI_CSIH2_TIRE_CAT2_ISRfunc,   /* SPI_CSIH2_TIRE_CAT2_ISR */
      &SPI_CSIH2_TIR_CAT2_ISRfunc,   /* SPI_CSIH2_TIR_CAT2_ISR */
      &SnsrMeasStrtIrqfunc,   /* SnsrMeasStrtIrq */
      &osOstmInterruptfunc,   /* osOstmInterrupt_c0 */
      &osSystemCat2ISRfunc,   /* osSystemCat2ISR */
      (osIsrFctType)0
   },
   /* Sub-Container 13, Cat 2 ISR nestable */
   {
      osdTRUE, /* CanIsrGlobalStatus */
      osdTRUE, /* CanIsrRxFifo */
      osdTRUE, /* CanIsrStatus_0 */
      osdTRUE, /* CanIsrStatus_1 */
      osdTRUE, /* CanIsrTx_0 */
      osdTRUE, /* CanIsrTx_1 */
      osdTRUE, /* MCU_ECM_EIC_CAT2_ISR */
      osdTRUE, /* SPI_CSIG0_TIC_CAT2_ISR */
      osdTRUE, /* SPI_CSIG0_TIRE_CAT2_ISR */
      osdTRUE, /* SPI_CSIG0_TIR_CAT2_ISR */
      osdTRUE, /* SPI_CSIH0_TIC_CAT2_ISR */
      osdTRUE, /* SPI_CSIH0_TIRE_CAT2_ISR */
      osdTRUE, /* SPI_CSIH0_TIR_CAT2_ISR */
      osdTRUE, /* SPI_CSIH2_TIC_CAT2_ISR */
      osdTRUE, /* SPI_CSIH2_TIRE_CAT2_ISR */
      osdTRUE, /* SPI_CSIH2_TIR_CAT2_ISR */
      osdTRUE, /* SnsrMeasStrtIrq */
      osdTRUE, /* osOstmInterrupt_c0 */
      osdFALSE, /* osSystemCat2ISR */
      (osuint8)0
   },
   /* Sub-Container 14, ProcessToCore */
   {
      0U, /* TASK osSystemExtendedTask */
      0U, /* TASK Task_InitBsw_Appl10 */
      0U, /* TASK Task_Init_Appl10 */
      0U, /* TASK Task_Init_Appl6 */
      0U, /* TASK Task_Shutdown_Appl0 */
      0U, /* TASK Task_4msBsw_Appl10 */
      0U, /* TASK Task_2msTmplMonr_Appl10 */
      0U, /* TASK Task_2ms_Appl10 */
      0U, /* TASK Task_2ms_Appl6 */
      0U, /* TASK Task_4ms_Appl10 */
      0U, /* TASK Task_10ms_Appl10 */
      0U, /* TASK Task_10ms_Appl6 */
      0U, /* TASK Task_10msBsw_Appl10 */
      0U, /* TASK Task_100ms_Appl10 */
      0U, /* TASK osSystemBasicTask */
      0U, /* ISR CanIsrGlobalStatus (Category = 2) */
      0U, /* ISR CanIsrRxFifo (Category = 2) */
      0U, /* ISR CanIsrStatus_0 (Category = 2) */
      0U, /* ISR CanIsrStatus_1 (Category = 2) */
      0U, /* ISR CanIsrTx_0 (Category = 2) */
      0U, /* ISR CanIsrTx_1 (Category = 2) */
      0U, /* ISR MCU_ECM_EIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIG0_TIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIG0_TIRE_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIG0_TIR_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH0_TIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH0_TIRE_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH0_TIR_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH2_TIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH2_TIRE_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH2_TIR_CAT2_ISR (Category = 2) */
      0U, /* ISR SnsrMeasStrtIrq (Category = 2) */
      0U, /* ISR osOstmInterrupt_c0 (Category = 2) */
      0U, /* ISR osSystemCat2ISR (Category = 2) */
      (CoreIdType)0
   },
   /* Sub-Container 15, AlarmToCore */
   {
      0U, 
      0U, 
      0U, 
      0U, 
      0U, 
      0U, 
      0U, 
      0U, 
      0U, 
      0U, 
      (CoreIdType)0
   },
   /* Sub-Container 16, ResourceToCore */
   {
      0U, 
      0U, 
      0U, 
      (CoreIdType)0
   },
   /* Sub-Container 17, CounterToCore */
   {
      0U, 
      0U, 
      (CoreIdType)0
   },
   /* Sub-Container 18, ScheduleTableToCore */
   {
      0U, 
      (CoreIdType)0
   },
   /* Sub-Container 19, ApplicationToCore */
   {
      0U, 
      0U, 
      0U, 
      0U, 
      (CoreIdType)0
   },
   /* Sub-Container 20, TrustedFunctionToCore */
   {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      (CoreIdType)0
   },
   /* Sub-Container 21, NonTrustedFunctionToCore */
   {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      (CoreIdType)0
   },
   /* Sub-Container 22, Core Control Block addresses */
   {
      &osCtrlVarsCore0,
      (osCtrlVarType*)0
   },
   /* Sub-Container 23, peripheral regions */
   {
      {(void*)0, (void*)0, 0}
   },
   /* Sub-Container 24, Spinlock lock method */
   {
      (osuint8)0
   },
   /* Sub-Container 25, Spinlock lock type */
   {
      (osuint8)0
   },
   /* Sub-Container 26, Optimized Spinlock variables */
   {
      (osMiniLockType*) osdNULL
   },
   /* Sub-Container 27 ISR stack information */
   {
      {
         (osStackPtrType)osdCanIsrGlobalStatus_BOT,
         (osStackPtrType)osdCanIsrGlobalStatus_TOP
      },
      {
         (osStackPtrType)osdCanIsrRxFifo_BOT,
         (osStackPtrType)osdCanIsrRxFifo_TOP
      },
      {
         (osStackPtrType)osdCanIsrStatus_0_BOT,
         (osStackPtrType)osdCanIsrStatus_0_TOP
      },
      {
         (osStackPtrType)osdCanIsrStatus_1_BOT,
         (osStackPtrType)osdCanIsrStatus_1_TOP
      },
      {
         (osStackPtrType)osdCanIsrTx_0_BOT,
         (osStackPtrType)osdCanIsrTx_0_TOP
      },
      {
         (osStackPtrType)osdCanIsrTx_1_BOT,
         (osStackPtrType)osdCanIsrTx_1_TOP
      },
      {
         (osStackPtrType)osdMCU_ECM_EIC_CAT2_ISR_BOT,
         (osStackPtrType)osdMCU_ECM_EIC_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIG0_TIC_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIG0_TIC_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIG0_TIRE_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIG0_TIRE_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIG0_TIR_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIG0_TIR_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIH0_TIC_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIH0_TIC_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIH0_TIRE_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIH0_TIRE_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIH0_TIR_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIH0_TIR_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIH2_TIC_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIH2_TIC_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIH2_TIRE_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIH2_TIRE_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSPI_CSIH2_TIR_CAT2_ISR_BOT,
         (osStackPtrType)osdSPI_CSIH2_TIR_CAT2_ISR_TOP
      },
      {
         (osStackPtrType)osdSnsrMeasStrtIrq_BOT,
         (osStackPtrType)osdSnsrMeasStrtIrq_TOP
      },
      {
         (osStackPtrType)osdosOstmInterrupt_c0_BOT,
         (osStackPtrType)osdosOstmInterrupt_c0_TOP
      },
      {
         (osStackPtrType)osdosSystemCat2ISR_BOT,
         (osStackPtrType)osdosSystemCat2ISR_TOP
      },
      {
         (osStackPtrType)0,
         (osStackPtrType)0
      }
   },

   /* Sub-Container 28: ISR interrupt channel index */
   {
      (osuint16)189, /* channel of CanIsrGlobalStatus */
      (osuint16)190, /* channel of CanIsrRxFifo */
      (osuint16)183, /* channel of CanIsrStatus_0 */
      (osuint16)186, /* channel of CanIsrStatus_1 */
      (osuint16)185, /* channel of CanIsrTx_0 */
      (osuint16)188, /* channel of CanIsrTx_1 */
      (osuint16)  8, /* channel of MCU_ECM_EIC_CAT2_ISR */
      (osuint16)175, /* channel of SPI_CSIG0_TIC_CAT2_ISR */
      (osuint16)174, /* channel of SPI_CSIG0_TIRE_CAT2_ISR */
      (osuint16)176, /* channel of SPI_CSIG0_TIR_CAT2_ISR */
      (osuint16) 84, /* channel of SPI_CSIH0_TIC_CAT2_ISR */
      (osuint16) 82, /* channel of SPI_CSIH0_TIRE_CAT2_ISR */
      (osuint16) 83, /* channel of SPI_CSIH0_TIR_CAT2_ISR */
      (osuint16)100, /* channel of SPI_CSIH2_TIC_CAT2_ISR */
      (osuint16) 98, /* channel of SPI_CSIH2_TIRE_CAT2_ISR */
      (osuint16) 99, /* channel of SPI_CSIH2_TIR_CAT2_ISR */
      (osuint16) 75, /* channel of SnsrMeasStrtIrq */
      (osuint16) 74, /* channel of osOstmInterrupt_c0 */
      (osuint16)  0, /* channel of osSystemCat2ISR */
      (osuint16) 16, /* channel of MotCtrlMgrIrq */
      (osuint16)  9, /* channel of WDG_59_DRIVERA_TRIGGERFUNCTION_ISR */
      (osuint16)  0  /* empty */
   },

   /* Sub-Container 29: ISR interrupt priority level */
   {
      (osuint16)0x000f, /* priority level of CanIsrGlobalStatus */
      (osuint16)0x000f, /* priority level of CanIsrRxFifo */
      (osuint16)0x000f, /* priority level of CanIsrStatus_0 */
      (osuint16)0x000f, /* priority level of CanIsrStatus_1 */
      (osuint16)0x000f, /* priority level of CanIsrTx_0 */
      (osuint16)0x000f, /* priority level of CanIsrTx_1 */
      (osuint16)0x0003, /* priority level of MCU_ECM_EIC_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIG0_TIC_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIG0_TIRE_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIG0_TIR_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIH0_TIC_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIH0_TIRE_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIH0_TIR_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIH2_TIC_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIH2_TIRE_CAT2_ISR */
      (osuint16)0x000e, /* priority level of SPI_CSIH2_TIR_CAT2_ISR */
      (osuint16)0x000d, /* priority level of SnsrMeasStrtIrq */
      (osuint16)0x0003, /* priority level of osOstmInterrupt_c0 */
      (osuint16)0x0080, /* priority level of osSystemCat2ISR is not initialized */
      (osuint16)0x0001, /* priority level of MotCtrlMgrIrq */
      (osuint16)0x0002, /* priority level of WDG_59_DRIVERA_TRIGGERFUNCTION_ISR */
      (osuint16)0x0000  /* empty */
   },

   /* Sub-Container 30: ISR to Core assignment */
   {
      0U, /* ISR CanIsrGlobalStatus (Category = 2) */
      0U, /* ISR CanIsrRxFifo (Category = 2) */
      0U, /* ISR CanIsrStatus_0 (Category = 2) */
      0U, /* ISR CanIsrStatus_1 (Category = 2) */
      0U, /* ISR CanIsrTx_0 (Category = 2) */
      0U, /* ISR CanIsrTx_1 (Category = 2) */
      0U, /* ISR MCU_ECM_EIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIG0_TIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIG0_TIRE_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIG0_TIR_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH0_TIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH0_TIRE_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH0_TIR_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH2_TIC_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH2_TIRE_CAT2_ISR (Category = 2) */
      0U, /* ISR SPI_CSIH2_TIR_CAT2_ISR (Category = 2) */
      0U, /* ISR SnsrMeasStrtIrq (Category = 2) */
      0U, /* ISR osOstmInterrupt_c0 (Category = 2) */
      0U, /* ISR osSystemCat2ISR (Category = 2) */
      0U, /* ISR MotCtrlMgrIrq (Category = 1) */
      0U, /* ISR WDG_59_DRIVERA_TRIGGERFUNCTION_ISR (Category = 1) */
      0U  /* empty */
   },

   /* Sub-Container 31: Application MPU configuration */
   {
      {  /* Trusted application Appl0 */
         (osuint32)0x10UL,
         (osuint32)0x00UL,
      },
      {  /* Non-trusted application Appl10 */
         (osuint32)&Appl10_StartAddr,
         (osuint32)&Appl10_EndAddr,
      },
      {  /* Non-trusted application Appl6 */
         (osuint32)&Appl6_StartAddr,
         (osuint32)&Appl6_EndAddr,
      },
      {  /* Trusted application osSystemApplicationCore0 */
         (osuint32)0x10UL,
         (osuint32)0x00UL,
      },
   },

   /* Sub-Container 32: OS MPU configuration */
   {
      /* Core 0 */
      {
         (osuint32)&osSystemStack_c0_StartAddr, /* MPU region 0 */
         (osuint32)&osSystemStack_c0_EndAddr-4,
         (osuint32)0xdbUL,
         (osuint32)0x10UL, /* MPU region 1 */
         (osuint32)0x00UL,
         (osuint32)0xdbUL,
         (osuint32)0x00000000UL, /* MPU region 2 */
         (osuint32)0x000ffffcUL,
         (osuint32)0x03ff00edUL,
         (osuint32)0xff000000UL, /* MPU region 3 */
         (osuint32)0xfffffffcUL,
         (osuint32)0x03ff00dbUL,
         (osuint32)&GeneralRam_StartAddr, /* MPU region 4 */
         (osuint32)&GeneralRam_EndAddr,
         (osuint32)0x03ff00d9UL,
         (osuint32)&StackRam_StartAddr, /* MPU region 5 */
         (osuint32)&StackRam_EndAddr,
         (osuint32)0x03ff00c9UL,
         (osuint32)&osGlobalShared_StartAddr, /* MPU region 6 */
         (osuint32)&osGlobalShared_EndAddr,
         (osuint32)0x03ff00dbUL,
         (osuint32)0x00UL, /* MPU region 7 */
         (osuint32)0x00UL,
         (osuint32)0x00UL,
         (osuint32)0x00UL, /* MPU region 8 */
         (osuint32)0x00UL,
         (osuint32)0x00UL,
         (osuint32)0x00UL, /* MPU region 9 */
         (osuint32)0x00UL,
         (osuint32)0x00UL,
         (osuint32)0x00UL, /* MPU region 10 */
         (osuint32)0x00UL,
         (osuint32)0x00UL,
         (osuint32)0x00UL, /* MPU region 11 */
         (osuint32)0x00UL,
         (osuint32)0x00UL,
      },
   },

   /* Sub-Container 33: Application MPU ASID configuration */
   {
         (osuint16)0x03ff, /* application Appl0 */
         (osuint16)0x03ff, /* application Appl10 */
         (osuint16)0x03ff, /* application Appl6 */
         (osuint16)0x03ff, /* application osSystemApplicationCore0 */
   },

   (osuint32)0 /* uiCheckSum */
};

#pragma ghs section rodata=default
#pragma ghs section rosdata=default

