/* file: C:/Hari/Work/SynergyProjects/T1xx_Synergy/BuildPrep/07.01.05_Work/Z_Work_1_8917_ShortTerm/GM_T1XX_EPS_RH850/generate/osStacks.c */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: C:/Users/nz2654/AppData/Local/Temp/DaVinci/Cfg-1345187/Generation/Cfg_Gen-1484071352018-0/OsProxyFiles-1484072167553-0/Os_ActiveEcuC.arxml */
/* Generation time: Tue Jan 10 13:16:12 2017 */
/* Unlimited license CBD1400351 for Nxtr Automotive, Project License, EPS */
/* Implementation: RH850_P1M */
/* Version of general code: 9.01.06 */
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osStacks.h"
#else
 #include <osStacks.h>
#endif

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel13_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel13_c0 [128]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel14_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel14_c0 [128]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel15_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel15_c0 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel3_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel3_c0 [128]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osSystemStack_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osSystemStack_c0 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl00"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl00 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl100"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl100 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl101"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl101 [512]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl102"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl102 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl103"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl103 [192]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl104"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl104 [512]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl105"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl105 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl106"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl106 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl107"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl107 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl108"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl108 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl60"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl60 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl61"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl61 [256]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackAppl62"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackAppl62 [512]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackosSystemApplicationCore00"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackosSystemApplicationCore00 [4]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStackosSystemApplicationCore01"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStackosSystemApplicationCore01 [4]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

