/* file: C:/Hari/Work/SynergyProjects/T1xx_Synergy/BuildPrep/07.01.05_Work/Z_Work_1_8917_ShortTerm/GM_T1XX_EPS_RH850/generate/osStacks.h */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: C:/Users/nz2654/AppData/Local/Temp/DaVinci/Cfg-1345187/Generation/Cfg_Gen-1484071352018-0/OsProxyFiles-1484072167553-0/Os_ActiveEcuC.arxml */
/* Generation time: Tue Jan 10 13:16:12 2017 */
/* Unlimited license CBD1400351 for Nxtr Automotive, Project License, EPS */
/* Implementation: RH850_P1M */
/* Version of general code: 9.01.06 */
/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with message 0883,
 * but there is a double include prevention and therefore the message is considered to be wrong. */
#if ! defined __OSSTACKS_H__   /* PRQA S 0883 EOF */ 
#define __OSSTACKS_H__
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osek.h"
#else
 #include <osek.h>
#endif

#define osdosSystemExtendedTask_BOT osBottomOfStack(osTaskStackosSystemApplicationCore00)
#define osdosSystemExtendedTask_TOP osAssignStack(osTaskStackosSystemApplicationCore00)

#define osdTask_InitBsw_Appl10_BOT osBottomOfStack(osTaskStackAppl100)
#define osdTask_InitBsw_Appl10_TOP osAssignStack(osTaskStackAppl100)

#define osdTask_Init_Appl10_BOT osBottomOfStack(osTaskStackAppl101)
#define osdTask_Init_Appl10_TOP osAssignStack(osTaskStackAppl101)

#define osdTask_Init_Appl6_BOT osBottomOfStack(osTaskStackAppl60)
#define osdTask_Init_Appl6_TOP osAssignStack(osTaskStackAppl60)

#define osdTask_Shutdown_Appl0_BOT osBottomOfStack(osTaskStackAppl00)
#define osdTask_Shutdown_Appl0_TOP osAssignStack(osTaskStackAppl00)

#define osdTask_4msBsw_Appl10_BOT osBottomOfStack(osTaskStackAppl102)
#define osdTask_4msBsw_Appl10_TOP osAssignStack(osTaskStackAppl102)

#define osdTask_2msTmplMonr_Appl10_BOT osBottomOfStack(osTaskStackAppl103)
#define osdTask_2msTmplMonr_Appl10_TOP osAssignStack(osTaskStackAppl103)

#define osdTask_2ms_Appl10_BOT osBottomOfStack(osTaskStackAppl104)
#define osdTask_2ms_Appl10_TOP osAssignStack(osTaskStackAppl104)

#define osdTask_2ms_Appl6_BOT osBottomOfStack(osTaskStackAppl61)
#define osdTask_2ms_Appl6_TOP osAssignStack(osTaskStackAppl61)

#define osdTask_4ms_Appl10_BOT osBottomOfStack(osTaskStackAppl105)
#define osdTask_4ms_Appl10_TOP osAssignStack(osTaskStackAppl105)

#define osdTask_10ms_Appl10_BOT osBottomOfStack(osTaskStackAppl106)
#define osdTask_10ms_Appl10_TOP osAssignStack(osTaskStackAppl106)

#define osdTask_10ms_Appl6_BOT osBottomOfStack(osTaskStackAppl62)
#define osdTask_10ms_Appl6_TOP osAssignStack(osTaskStackAppl62)

#define osdTask_10msBsw_Appl10_BOT osBottomOfStack(osTaskStackAppl107)
#define osdTask_10msBsw_Appl10_TOP osAssignStack(osTaskStackAppl107)

#define osdTask_100ms_Appl10_BOT osBottomOfStack(osTaskStackAppl108)
#define osdTask_100ms_Appl10_TOP osAssignStack(osTaskStackAppl108)

#define osdosSystemBasicTask_BOT osBottomOfStack(osTaskStackosSystemApplicationCore01)
#define osdosSystemBasicTask_TOP osAssignStack(osTaskStackosSystemApplicationCore01)

#define osdSystemStack_c0_BOT osBottomOfStack(osSystemStack_c0)
#define osdSystemStack_c0_TOP osAssignStack(osSystemStack_c0)

#define osdCanIsrGlobalStatus_BOT osBottomOfStack(osIntStackLevel15_c0)
#define osdCanIsrGlobalStatus_TOP osAssignStack(osIntStackLevel15_c0)

#define osdCanIsrRxFifo_BOT osBottomOfStack(osIntStackLevel15_c0)
#define osdCanIsrRxFifo_TOP osAssignStack(osIntStackLevel15_c0)

#define osdCanIsrStatus_0_BOT osBottomOfStack(osIntStackLevel15_c0)
#define osdCanIsrStatus_0_TOP osAssignStack(osIntStackLevel15_c0)

#define osdCanIsrStatus_1_BOT osBottomOfStack(osIntStackLevel15_c0)
#define osdCanIsrStatus_1_TOP osAssignStack(osIntStackLevel15_c0)

#define osdCanIsrTx_0_BOT osBottomOfStack(osIntStackLevel15_c0)
#define osdCanIsrTx_0_TOP osAssignStack(osIntStackLevel15_c0)

#define osdCanIsrTx_1_BOT osBottomOfStack(osIntStackLevel15_c0)
#define osdCanIsrTx_1_TOP osAssignStack(osIntStackLevel15_c0)

#define osdMCU_ECM_EIC_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel3_c0)
#define osdMCU_ECM_EIC_CAT2_ISR_TOP osAssignStack(osIntStackLevel3_c0)

#define osdSPI_CSIG0_TIC_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIG0_TIC_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIG0_TIRE_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIG0_TIRE_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIG0_TIR_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIG0_TIR_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIH0_TIC_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIH0_TIC_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIH0_TIRE_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIH0_TIRE_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIH0_TIR_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIH0_TIR_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIH2_TIC_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIH2_TIC_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIH2_TIRE_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIH2_TIRE_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSPI_CSIH2_TIR_CAT2_ISR_BOT osBottomOfStack(osIntStackLevel14_c0)
#define osdSPI_CSIH2_TIR_CAT2_ISR_TOP osAssignStack(osIntStackLevel14_c0)

#define osdSnsrMeasStrtIrq_BOT osBottomOfStack(osIntStackLevel13_c0)
#define osdSnsrMeasStrtIrq_TOP osAssignStack(osIntStackLevel13_c0)

#define osdosOstmInterrupt_c0_BOT osBottomOfStack(osIntStackLevel3_c0)
#define osdosOstmInterrupt_c0_TOP osAssignStack(osIntStackLevel3_c0)

#define osdosSystemCat2ISR_BOT ((osStackDataType*)0)
#define osdosSystemCat2ISR_TOP ((osStackDataType*)0)

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osIntStackLevel13_c0 [128]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osIntStackLevel14_c0 [128]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osIntStackLevel15_c0 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osIntStackLevel3_c0 [128]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osSystemStack_c0 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl00 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl100 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl101 [512]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl102 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl103 [192]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl104 [512]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl105 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl106 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl107 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl108 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl60 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl61 [256]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackAppl62 [512]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackosSystemApplicationCore00 [4]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#pragma ghs startdata
#pragma alignvar(4)
/*
 * MISRA RULE 5.1 VIOLATION: The names of the stacks are combined
 * from a prefix, the application name and a
 * sequential number. Depending on the application name, this might
 * result in a name with more than 31 characters, differing only in the
 * sequential number at the end (777).
 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackosSystemApplicationCore01 [4]; /* PRQA S 0777 */ /* PRQA S 4152 */ 
#pragma ghs enddata

#endif /* ! defined __OSSTACKS_H__ */
