/* file: C:/Hari/Work/SynergyProjects/T1xx_Synergy/BuildPrep/07.01.05_Work/Z_Work_1_8917_ShortTerm/GM_T1XX_EPS_RH850/generate/tcb.h */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: C:/Users/nz2654/AppData/Local/Temp/DaVinci/Cfg-1345187/Generation/Cfg_Gen-1484071352018-0/OsProxyFiles-1484072167553-0/Os_ActiveEcuC.arxml */
/* Generation time: Tue Jan 10 13:16:13 2017 */
/* Unlimited license CBD1400351 for Nxtr Automotive, Project License, EPS */
/* Implementation: RH850_P1M */
/* Version of general code: 9.01.06 */
/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with message 0883,
 * but there is a double include prevention and therefore the message is considered to be wrong. */
#if ! defined __TCB_H__   /* PRQA S 0883 EOF */ 
#define __TCB_H__
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdNumberOfAlarmsOnHiResCounter 0

#define osdUseHighResolutionTimer 0

#define osdHwTimerNeeded_OSTM 1
#define osdHwTimerNeeded_OSTM_HIRES 0

#define osdHardwareTimerNeeded 1
#define osdGetCurrentTimeHighResHybridIdx -1
#define osdGetCurrentTimeHighResMonoIdx -1
#define osdGetCurrentTimeStdIdx -1
#define osdSetTIPAbsMaxGtSemiCountIdx -1
#define osdSetTIPAbsMaxLeSemiCountIdx -1
#define osdSetTIPRelMaxGtSemiCountIdx -1
#define osdSetTIPRelMaxLeSemiCountIdx -1
#define osdClearTIPAbsIdx -1
#define osdClearTIPRelIdx -1
#define osdHandleCounterInterruptHiResIdx -1
#define osdHandleCounterInterruptStdIdx 0
#define osdInsertMinHeapHiResIdx -1
#define osdInsertMinHeapStdIdx 0
#define osdORTIDebug 1
#define osdORTIVersion  not used anymore!
#define osdORTIStdVersion 220
#define osdORTIEnabled 1
#define osdNumberOfScheduleTables 1
#define osdNumberOfHiResSchedTabs 0
#define osdScheduleTableSyncUsed 0
#define osdNumberOfSTExpiryPoints 2
#define osdNumberOfSTSetEvent 1
#define osdNumberOfSTActivateTask 1
#define osdNumberOfSTEntries 3
#define osdCallTimingHooks 0
#define osdTimingHooksFileName ""
#define osdRH850_P1M

#define osdExceptionDetails  0

#define osdRH850_FPU   1

#define OS_CHECK_INTAPISTATUS   1

#define CanIsrGlobalStatus_index  0
#define CanIsrRxFifo_index  1
#define CanIsrStatus_0_index  2
#define CanIsrStatus_1_index  3
#define CanIsrTx_0_index  4
#define CanIsrTx_1_index  5
#define MCU_ECM_EIC_CAT2_ISR_index  6
#define SPI_CSIG0_TIC_CAT2_ISR_index  7
#define SPI_CSIG0_TIRE_CAT2_ISR_index  8
#define SPI_CSIG0_TIR_CAT2_ISR_index  9
#define SPI_CSIH0_TIC_CAT2_ISR_index  10
#define SPI_CSIH0_TIRE_CAT2_ISR_index  11
#define SPI_CSIH0_TIR_CAT2_ISR_index  12
#define SPI_CSIH2_TIC_CAT2_ISR_index  13
#define SPI_CSIH2_TIRE_CAT2_ISR_index  14
#define SPI_CSIH2_TIR_CAT2_ISR_index  15
#define SnsrMeasStrtIrq_index  16
#define osOstmInterrupt_c0_index  17
#define osSystemCat2ISR_index  18
#define osdISRHooks            0

#define osdNumberOfPrioLevels  16
#define osdNumberOfInterrupts  384

#define osdSystemLevel         3
#define osdSystemLevelMask     0x0000fff8UL
#define osdSystemStackSize     1024
#define osdStackCheckPattern   0xaaaaaaaaUL

#define osdNumberOfMpuRegions  12
#define osdNumberOfDynamicMpuRegions_c0   1
#define osdNumberOfStaticMpuRegions    5

#define osdOnCore                  0
#define osdNumberOfAvailableCores  1
#define osdTimerCompareRegValCore0 0x000270ff
#define osdTimerInterruptSourceNumberCore0 74
#define CC ECC2
#define STATUS_LEVEL EXTENDED_STATUS
#define osdByteSize 8U
#define osdCompiler osdCompilerGHSRH850
#define osdFullPreempt 0
#define osdLib 0
#define osdMixedPreempt 1
#define osdNeedIOCTypes 0
#define osdNonPreempt 0
#define osdNumApplErrorHooks 0
#define osdNumApplShutdownHooks 0
#define osdNumApplStartupHooks 0
#define osdNumberOfAllResources 3
#define osdNumberOfBasicTasks 14
#define osdNumberOfExtendedTasks 1
#define osdNumberOfIOCCommunications 0
#define osdNumberOfInternalResources 0
#define osdNumberOfInterruptResources 0
#define osdNumberOfPriorities 17
#define osdNumberOfQueuedIOCCallbacks 0
#define osdNumberOfQueuedIOCCommunications 0
#define osdNumberOfSemaphores 1
#define osdNumberOfTaskResources 3
#define osdRTSize 1
#define osdReducedStatusChecks 0
#define osdResAccessMaskBits 32
#define osdSC SC3
#define osdSysErrorHook 1
#define osdSysShutdownHook 1
#define osdSysStartupHook 1
#define osdTimingProtectionUsed 0
#define osdUseIOC 0
#define osdNumberOfAllISRs  21
#define osdNumberOfAllTasks 15
#define osdNumberOfCat1ISRs 2
#define osdNumberOfCat2ISRs 19
#define osdNumberOfNonTrustedFunctions 30
#define osdNumberOfPeripheralRegions 0
#define osdNumberOfTrustedFunctions 15
#define osdUseTrustedFunctionStubs 1
#define osdNumberOfAlarms 10
#define osdNumberOfAlarmCallback 0
#define osdNumberOfAlarmSetEvent 0
#define osdNumberOfAlarmActivateTask 9
#define osdNumberOfAlarmIncrementCounter 1
#define osdNumberOfCounters 2
#define osdNumberOfSWCounters 1
#define osdNumberOfSWAndSRCounters 2
#define osdNumberOfApplications 4
#define osdStackCheck 1
#define osdStackUsageMeasurement 1

#define osdTypeHeaderInclude 1

#define osdEnableAssertions 1

#define osdGetServiceIdMacros 0
#define osdParameterAccessMacros 0

#define osdTimingMeasurement 0
#define osdProtectAndMeasureAll 0
#define osdAsSelected 0
#define osdOnlyMeasureAll 0

#define osdProtReactKillTaskIsrAllowed  0
#define osdProtReactKillApplAllowed     0
#define osdProtReactKillApplRestAllowed 0
#define osdErrorHook 1
#define osdPreTaskHook 0
#define osdPostTaskHook 0
#define osdShutdownHook 1
#define osdProtectionHook 1

  #define osdKillTaskIsrPossible 0
  #define osdKillApplPossible 0
#define osdNumberOfProcesses (osdNumberOfAllTasks+osdNumberOfCat2ISRs)

#endif /* ! defined __TCB_H__ */
