/*** Generated code, do not change!                                        ***/
/*** Module WdgM_OsMemMap, written by Wdg_Mgr_Cfg_Gen 3.3.15 (build        ***/
/*** 253626) on Wed 14-Dec-2016 13:17:00                                   ***/





/* Supervised Entity SE_10msBsw_Appl10                                       */
#ifdef WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE0_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE0_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE_10msBsw_Appl10` has an Alive Counter                */
#ifdef WDGM_SE0_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE0_START_SEC_VAR_NOINIT_32BIT 
  #define Appl10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE0_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE0_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE0_STOP_SEC_VAR_NOINIT_32BIT 
  #define Appl10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE0_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE_2ms_Appl10                                           */
#ifdef WDGM_SE1_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE1_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE1_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE1_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE1_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE1_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE_2ms_Appl10` has an Alive Counter                    */
#ifdef WDGM_SE1_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE1_START_SEC_VAR_NOINIT_32BIT 
  #define Appl10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE1_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE1_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE1_STOP_SEC_VAR_NOINIT_32BIT 
  #define Appl10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE1_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE_2ms_Appl6                                            */
#ifdef WDGM_SE2_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE2_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl6_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE2_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE2_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl6_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE_2ms_Appl6` has an Alive Counter                     */
#ifdef WDGM_SE2_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE2_START_SEC_VAR_NOINIT_32BIT 
  #define Appl6_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE2_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE2_STOP_SEC_VAR_NOINIT_32BIT 
  #define Appl6_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE2_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE_100ms_Appl10                                         */
#ifdef WDGM_SE3_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE3_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE3_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE3_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE3_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE3_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE_100ms_Appl10` has an Alive Counter                  */
#ifdef WDGM_SE3_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE3_START_SEC_VAR_NOINIT_32BIT 
  #define Appl10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE3_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE3_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE3_STOP_SEC_VAR_NOINIT_32BIT 
  #define Appl10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE3_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE_10ms_Appl6                                           */
#ifdef WDGM_SE4_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE4_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl6_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE4_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE4_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE4_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl6_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE4_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


/* Supervised Entity SE_4ms_Appl10                                           */
#ifdef WDGM_SE5_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE5_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE5_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE5_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE_4ms_Appl10` has an Alive Counter                    */
#ifdef WDGM_SE5_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE5_START_SEC_VAR_NOINIT_32BIT 
  #define Appl10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE5_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE5_STOP_SEC_VAR_NOINIT_32BIT 
  #define Appl10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE5_STOP_SEC_VAR_NOINIT_32BIT */


/* Supervised Entity SE_10ms_Appl10                                          */
#ifdef WDGM_SE6_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE6_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE6_START_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_SE6_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

/* Supervised Entity `SE_10ms_Appl10` has an Alive Counter                   */
#ifdef WDGM_SE6_START_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE6_START_SEC_VAR_NOINIT_32BIT 
  #define Appl10_START_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE6_START_SEC_VAR_NOINIT_32BIT */

#ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_32BIT
  #undef WDGM_SE6_STOP_SEC_VAR_NOINIT_32BIT 
  #define Appl10_STOP_SEC_VAR_NOINIT_32BIT 
#endif /* ifdef WDGM_SE6_STOP_SEC_VAR_NOINIT_32BIT */


/* S-WdgM global data section, read by all modules (tasks), written by       */
/* WdgM_MainFunction() and WdgM_Init() only                                  */
#ifdef WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_START_SEC_VAR_NOINIT_UNSPECIFIED */
#ifdef WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define Appl10_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_STOP_SEC_VAR_NOINIT_UNSPECIFIED */

#ifdef WDGM_GLOBAL_START_SEC_VAR_32BIT
  #undef WDGM_GLOBAL_START_SEC_VAR_32BIT 
  #define Appl10_START_SEC_VAR_32BIT 
#endif /* ifdef WDGM_GLOBAL_START_SEC_VAR_32BIT */
#ifdef WDGM_GLOBAL_STOP_SEC_VAR_32BIT
  #undef WDGM_GLOBAL_STOP_SEC_VAR_32BIT 
  #define Appl10_STOP_SEC_VAR_32BIT 
#endif /* ifdef WDGM_GLOBAL_STOP_SEC_VAR_32BIT */

#ifdef WDGM_GLOBAL_START_SEC_VAR_BOOLEAN
  #undef WDGM_GLOBAL_START_SEC_VAR_BOOLEAN 
  #define Appl10_START_SEC_VAR_BOOLEAN 
#endif /* ifdef WDGM_GLOBAL_START_SEC_VAR_BOOLEAN */
#ifdef WDGM_GLOBAL_STOP_SEC_VAR_BOOLEAN
  #undef WDGM_GLOBAL_STOP_SEC_VAR_BOOLEAN 
  #define Appl10_STOP_SEC_VAR_BOOLEAN 
#endif /* ifdef WDGM_GLOBAL_STOP_SEC_VAR_BOOLEAN */

/* S-WdgM global shared data section, read and write by all modules (tasks). */
/* WdgM read:  WdgM_CheckpointReached() and WdgM_MainFunction() WdgM write:  */
/* WdgM_CheckpointReached() and WdgM_Init()                                  */
#ifdef WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED 
  #define GlobalShared_START_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_SHARED_START_SEC_VAR_NOINIT_UNSPECIFIED */
#ifdef WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED
  #undef WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
  #define GlobalShared_STOP_SEC_VAR_NOINIT_UNSPECIFIED 
#endif /* ifdef WDGM_GLOBAL_SHARED_STOP_SEC_VAR_NOINIT_UNSPECIFIED */


