/**********************************************************************************************************************
* Module File Name  : pbg_regs.h
* Module Description: Peripheral Guard Peripheral Registers
* Project           : CBD
* Author            : Lucas Wendling
***********************************************************************************************************************
* Version Control:
* %version:          2 %
* %derived_by:       czgng4 %
*----------------------------------------------------------------------------
* Date      Rev      Author         Change Description
* -------   -------  --------  ----------------------------------------------
* 12/16/14  1        LWW       Initial version derived from dr7f701311.dvf.h v1 in tools directory
* 09/14/15  2        NJS       Updated to account for changes in dr7f701311.dvf.h v2 in tools directory
**********************************************************************************************************************/

#ifndef PBG_REGS_H
#define PBG_REGS_H

/**********************************************************************************************************************
* Include files
 *********************************************************************************************************************/
#include "Std_Types.h"
#include "reg_common.h"

typedef struct 
{                                                          /* Bit Access       */
    uint8  PROTWR:1;                                       /* PROTWR           */
    uint8  PROTRD:1;                                       /* PROTRD           */
    uint8  PROTWRPDEF:1;                                   /* PROTWRPDEF       */
    uint8  PROTRDPDEF:1;                                   /* PROTRDPDEF       */
    uint8  PROTDEB:1;                                      /* PROTDEB          */
    uint16 PROTSPID:4;                                     /* PROTSPID[8:5]    */
    uint8  :7;                                             /* Reserved Bits    */
    uint8  :1;                                             /* Reserved Bits    */
    uint16 PROTPEID:8;                                     /* PROTPEID[24:17]  */
    uint8  PROTUM:1;                                       /* PROTUM           */
    uint8  :6;                                             /* Reserved Bits    */
} __type340;
typedef struct 
{                                                          /* Bit Access       */
    uint8  CLRE:1;                                         /* CLRE             */
    uint8  CLRO:1;                                         /* CLRO             */
    uint8  :6;                                             /* Reserved Bits    */
    uint8  :8;                                             /* Reserved Bits    */
    uint8  :8;                                             /* Reserved Bits    */
    uint8  :8;                                             /* Reserved Bits    */
} __type341;
typedef struct 
{                                                          /* Bit Access       */
    const uint8  ERR:1;                                    /* ERR              */
    const uint8  OVF:1;                                    /* OVF              */
    uint8  :6;                                             /* Reserved Bits    */
    uint8  :8;                                             /* Reserved Bits    */
    uint8  :8;                                             /* Reserved Bits    */
    uint8  :8;                                             /* Reserved Bits    */
} __type342;
typedef struct 
{                                                          /* Bit Access       */
    const uint32 ADDR:32;                                  /* ADDR[31:0]       */
} __type343;
typedef struct 
{                                                          /* Bit Access       */
    const uint16 WRITE:1;                                  /* WRITE            */
    const uint16 STRB:4;                                   /* STRB[4:1]        */
    uint16 :1;                                             /* Reserved Bits    */
    const uint16 UM:1;                                     /* UM               */
    uint16 :1;                                             /* Reserved Bits    */
    const uint16 SPID:2;                                   /* SPID[9:8]        */
    uint16 :3;                                             /* Reserved Bits    */
    const uint16 PEID:3;                                   /* PEID[15:13]      */
    uint16 :16;                                            /* Reserved Bits    */
} __type344;

typedef union
{                                                          /* IOR              */
    uint32 UINT32;                                         /* 32-bit Access    */
    uint16 UINT16[2];                                      /* 16-bit Access    */
    uint8  UINT8[4];                                       /* 8-bit Access     */
    __type340 BIT;                                         /* Bit Access       */
} __type1619;
typedef union
{                                                          /* IOR              */
    uint32 UINT32;                                         /* 32-bit Access    */
    uint16 UINT16[2];                                      /* 16-bit Access    */
    uint8  UINT8[4];                                       /* 8-bit Access     */
    __type341 BIT;                                         /* Bit Access       */
} __type1620;
typedef union
{                                                          /* IOR              */
    uint32 UINT32;                                         /* 32-bit Access    */
    uint16 UINT16[2];                                      /* 16-bit Access    */
    uint8  UINT8[4];                                       /* 8-bit Access     */
    const __type342 BIT;                                   /* Bit Access       */
} __type1621;
typedef union
{                                                          /* IOR              */
    uint32 UINT32;                                         /* 32-bit Access    */
    const __type343 BIT;                                   /* Bit Access       */
} __type1622;
typedef union
{                                                          /* IOR              */
    uint32 UINT32;                                         /* 32-bit Access    */
    uint16 UINT16[2];                                      /* 16-bit Access    */
    const __type344 BIT;                                   /* Bit Access       */
} __type1623;

typedef struct 
{                                                          /* Module           */
    __type1619 FSGD3ADPROT0;                               /* FSGD3ADPROT0     */
    __type1619 FSGD3ADPROT1;                               /* FSGD3ADPROT1     */
    __type1619 FSGD3ADPROT2;                               /* FSGD3ADPROT2     */
    __type1619 FSGD3ADPROT3;                               /* FSGD3ADPROT3     */
    __type1619 FSGD3ADPROT4;                               /* FSGD3ADPROT4     */
    __type1619 FSGD3ADPROT5;                               /* FSGD3ADPROT5     */
    __type1619 FSGD3ADPROT6;                               /* FSGD3ADPROT6     */
    __type1619 FSGD3ADPROT7;                               /* FSGD3ADPROT7     */
    __type1619 FSGD3ADPROT8;                               /* FSGD3ADPROT8     */
    __type1619 FSGD3ADPROT9;                               /* FSGD3ADPROT9     */
    __type1619 FSGD3ADPROT10;                              /* FSGD3ADPROT10    */
    __type1619 FSGD3ADPROT11;                              /* FSGD3ADPROT11    */
    uint8  dummy202[16];                                   /* Reserved         */
    __type1620 ERRSLV3ACTL;                                /* ERRSLV3ACTL      */
    const __type1621 ERRSLV3ASTAT;                         /* ERRSLV3ASTAT     */
    const __type1622 ERRSLV3AADDR;                         /* ERRSLV3AADDR     */
    const __type1623 ERRSLV3ATYPE;                         /* ERRSLV3ATYPE     */
    uint8  dummy203[49072];                                /* Reserved         */
    __type1619 FSGD0ADPROT0;                               /* FSGD0ADPROT0     */
    __type1619 FSGD0ADPROT1;                               /* FSGD0ADPROT1     */
    uint8  dummy204[2040];                                 /* Reserved         */
    __type1620 ERRSLV0ACTL;                                /* ERRSLV0ACTL      */
    const __type1621 ERRSLV0ASTAT;                         /* ERRSLV0ASTAT     */
    const __type1622 ERRSLV0AADDR;                         /* ERRSLV0AADDR     */
    const __type1623 ERRSLV0ATYPE;                         /* ERRSLV0ATYPE     */
    uint8  dummy205[1640432];                              /* Reserved         */
    __type1619 FSGD1ADPROT0;                               /* FSGD1ADPROT0     */
    __type1619 FSGD1ADPROT1;                               /* FSGD1ADPROT1     */
    __type1619 FSGD1ADPROT2;                               /* FSGD1ADPROT2     */
    __type1619 FSGD1ADPROT3;                               /* FSGD1ADPROT3     */
    __type1619 FSGD1ADPROT4;                               /* FSGD1ADPROT4     */
    __type1619 FSGD1ADPROT5;                               /* FSGD1ADPROT5     */
    __type1619 FSGD1ADPROT6;                               /* FSGD1ADPROT6     */
    __type1619 FSGD1ADPROT7;                               /* FSGD1ADPROT7     */
    __type1619 FSGD1ADPROT8;                               /* FSGD1ADPROT8     */
    __type1619 FSGD1ADPROT9;                               /* FSGD1ADPROT9     */
    __type1619 FSGD1ADPROT10;                              /* FSGD1ADPROT10    */
    __type1619 FSGD1ADPROT11;                              /* FSGD1ADPROT11    */
    __type1619 FSGD1ADPROT12;                              /* FSGD1ADPROT12    */
    __type1619 FSGD1ADPROT13;                              /* FSGD1ADPROT13    */
    __type1619 FSGD1ADPROT14;                              /* FSGD1ADPROT14    */
    uint8  dummy206[4];                                    /* Reserved         */
    __type1620 ERRSLV1ACTL;                                /* ERRSLV1ACTL      */
    const __type1621 ERRSLV1ASTAT;                         /* ERRSLV1ASTAT     */
    const __type1622 ERRSLV1AADDR;                         /* ERRSLV1AADDR     */
    const __type1623 ERRSLV1ATYPE;                         /* ERRSLV1ATYPE     */
    uint8  dummy207[48];                                   /* Reserved         */
    __type1619 FSGD1BDPROT0;                               /* FSGD1BDPROT0     */
    __type1619 FSGD1BDPROT1;                               /* FSGD1BDPROT1     */
    __type1619 FSGD1BDPROT2;                               /* FSGD1BDPROT2     */
    __type1619 FSGD1BDPROT3;                               /* FSGD1BDPROT3     */
    __type1619 FSGD1BDPROT4;                               /* FSGD1BDPROT4     */
    __type1619 FSGD1BDPROT5;                               /* FSGD1BDPROT5     */
    __type1619 FSGD1BDPROT6;                               /* FSGD1BDPROT6     */
    __type1619 FSGD1BDPROT7;                               /* FSGD1BDPROT7     */
    __type1619 FSGD1BDPROT8;                               /* FSGD1BDPROT8     */
    __type1619 FSGD1BDPROT9;                               /* FSGD1BDPROT9     */
    __type1619 FSGD1BDPROT10;                              /* FSGD1BDPROT10    */
    __type1619 FSGD1BDPROT11;                              /* FSGD1BDPROT11    */
    __type1619 FSGD1BDPROT12;                              /* FSGD1BDPROT12    */
    __type1619 FSGD1BDPROT13;                              /* FSGD1BDPROT13    */
    __type1619 FSGD1BDPROT14;                              /* FSGD1BDPROT14    */
    uint8  dummy208[4];                                    /* Reserved         */
    __type1620 ERRSLV1BCTL;                                /* ERRSLV1BCTL      */
    const __type1621 ERRSLV1BSTAT;                         /* ERRSLV1BSTAT     */
    const __type1622 ERRSLV1BADDR;                         /* ERRSLV1BADDR     */
    const __type1623 ERRSLV1BTYPE;                         /* ERRSLV1BTYPE     */
    uint8  dummy209[1781552];                              /* Reserved         */
    __type1619 FSGD5ADPROT0;                               /* FSGD5ADPROT0     */
    uint8  dummy210[60];                                   /* Reserved         */
    __type1620 ERRSLV5ACTL;                                /* ERRSLV5ACTL      */
    const __type1621 ERRSLV5ASTAT;                         /* ERRSLV5ASTAT     */
    const __type1622 ERRSLV5AADDR;                         /* ERRSLV5AADDR     */
    const __type1623 ERRSLV5ATYPE;                         /* ERRSLV5ATYPE     */
    uint8  dummy211[16304];                                /* Reserved         */
    __type1619 FSGD2ADPROT0;                               /* FSGD2ADPROT0     */
    __type1619 FSGD2ADPROT1;                               /* FSGD2ADPROT1     */
    __type1619 FSGD2ADPROT2;                               /* FSGD2ADPROT2     */
    __type1619 FSGD2ADPROT3;                               /* FSGD2ADPROT3     */
    __type1619 FSGD2ADPROT4;                               /* FSGD2ADPROT4     */
    __type1619 FSGD2ADPROT5;                               /* FSGD2ADPROT5     */
    __type1619 FSGD2ADPROT6;                               /* FSGD2ADPROT6     */
    __type1619 FSGD2ADPROT7;                               /* FSGD2ADPROT7     */
    __type1619 FSGD2ADPROT8;                               /* FSGD2ADPROT8     */
    __type1619 FSGD2ADPROT9;                               /* FSGD2ADPROT9     */
    __type1619 FSGD2ADPROT10;                              /* FSGD2ADPROT10    */
    __type1619 FSGD2ADPROT11;                              /* FSGD2ADPROT11    */
    __type1619 FSGD2ADPROT12;                              /* FSGD2ADPROT12    */
    __type1619 FSGD2ADPROT13;                              /* FSGD2ADPROT13    */
    __type1619 FSGD2ADPROT14;                              /* FSGD2ADPROT14    */
    __type1619 FSGD2ADPROT15;                              /* FSGD2ADPROT15    */
    __type1620 ERRSLV2ACTL;                                /* ERRSLV2ACTL      */
    const __type1621 ERRSLV2ASTAT;                         /* ERRSLV2ASTAT     */
    const __type1622 ERRSLV2AADDR;                         /* ERRSLV2AADDR     */
    const __type1623 ERRSLV2ATYPE;                         /* ERRSLV2ATYPE     */
} __type2578;

__IOREG(PBG, 0xFFC40000, __READ_WRITE, __type2578);                   /* PBG */

#define PBGFSGD3ADPROT0 PBG.FSGD3ADPROT0.UINT32
#define PBGFSGD3ADPROT0L PBG.FSGD3ADPROT0.UINT16[L]
#define PBGFSGD3ADPROT0LL PBG.FSGD3ADPROT0.UINT8[LL]
#define PBGFSGD3ADPROT0LH PBG.FSGD3ADPROT0.UINT8[LH]
#define PBGFSGD3ADPROT0H PBG.FSGD3ADPROT0.UINT16[H]
#define PBGFSGD3ADPROT0HL PBG.FSGD3ADPROT0.UINT8[HL]
#define PBGFSGD3ADPROT0HH PBG.FSGD3ADPROT0.UINT8[HH]
#define PBGPROTWR PBG.FSGD3ADPROT0.BIT.PROTWR
#define PBGPROTRD PBG.FSGD3ADPROT0.BIT.PROTRD
#define PBGPROTWRPDEF PBG.FSGD3ADPROT0.BIT.PROTWRPDEF
#define PBGPROTRDPDEF PBG.FSGD3ADPROT0.BIT.PROTRDPDEF
#define PBGPROTDEB PBG.FSGD3ADPROT0.BIT.PROTDEB
#define PBGPROTSPID PBG.FSGD3ADPROT0.BIT.PROTSPID
#define PBGPROTPEID PBG.FSGD3ADPROT0.BIT.PROTPEID
#define PBGPROTUM PBG.FSGD3ADPROT0.BIT.PROTUM
#define PBGFSGD3ADPROT1 PBG.FSGD3ADPROT1.UINT32
#define PBGFSGD3ADPROT1L PBG.FSGD3ADPROT1.UINT16[L]
#define PBGFSGD3ADPROT1LL PBG.FSGD3ADPROT1.UINT8[LL]
#define PBGFSGD3ADPROT1LH PBG.FSGD3ADPROT1.UINT8[LH]
#define PBGFSGD3ADPROT1H PBG.FSGD3ADPROT1.UINT16[H]
#define PBGFSGD3ADPROT1HL PBG.FSGD3ADPROT1.UINT8[HL]
#define PBGFSGD3ADPROT1HH PBG.FSGD3ADPROT1.UINT8[HH]
#define PBGFSGD3ADPROT2 PBG.FSGD3ADPROT2.UINT32
#define PBGFSGD3ADPROT2L PBG.FSGD3ADPROT2.UINT16[L]
#define PBGFSGD3ADPROT2LL PBG.FSGD3ADPROT2.UINT8[LL]
#define PBGFSGD3ADPROT2LH PBG.FSGD3ADPROT2.UINT8[LH]
#define PBGFSGD3ADPROT2H PBG.FSGD3ADPROT2.UINT16[H]
#define PBGFSGD3ADPROT2HL PBG.FSGD3ADPROT2.UINT8[HL]
#define PBGFSGD3ADPROT2HH PBG.FSGD3ADPROT2.UINT8[HH]
#define PBGFSGD3ADPROT3 PBG.FSGD3ADPROT3.UINT32
#define PBGFSGD3ADPROT3L PBG.FSGD3ADPROT3.UINT16[L]
#define PBGFSGD3ADPROT3LL PBG.FSGD3ADPROT3.UINT8[LL]
#define PBGFSGD3ADPROT3LH PBG.FSGD3ADPROT3.UINT8[LH]
#define PBGFSGD3ADPROT3H PBG.FSGD3ADPROT3.UINT16[H]
#define PBGFSGD3ADPROT3HL PBG.FSGD3ADPROT3.UINT8[HL]
#define PBGFSGD3ADPROT3HH PBG.FSGD3ADPROT3.UINT8[HH]
#define PBGFSGD3ADPROT4 PBG.FSGD3ADPROT4.UINT32
#define PBGFSGD3ADPROT4L PBG.FSGD3ADPROT4.UINT16[L]
#define PBGFSGD3ADPROT4LL PBG.FSGD3ADPROT4.UINT8[LL]
#define PBGFSGD3ADPROT4LH PBG.FSGD3ADPROT4.UINT8[LH]
#define PBGFSGD3ADPROT4H PBG.FSGD3ADPROT4.UINT16[H]
#define PBGFSGD3ADPROT4HL PBG.FSGD3ADPROT4.UINT8[HL]
#define PBGFSGD3ADPROT4HH PBG.FSGD3ADPROT4.UINT8[HH]
#define PBGFSGD3ADPROT5 PBG.FSGD3ADPROT5.UINT32
#define PBGFSGD3ADPROT5L PBG.FSGD3ADPROT5.UINT16[L]
#define PBGFSGD3ADPROT5LL PBG.FSGD3ADPROT5.UINT8[LL]
#define PBGFSGD3ADPROT5LH PBG.FSGD3ADPROT5.UINT8[LH]
#define PBGFSGD3ADPROT5H PBG.FSGD3ADPROT5.UINT16[H]
#define PBGFSGD3ADPROT5HL PBG.FSGD3ADPROT5.UINT8[HL]
#define PBGFSGD3ADPROT5HH PBG.FSGD3ADPROT5.UINT8[HH]
#define PBGFSGD3ADPROT6 PBG.FSGD3ADPROT6.UINT32
#define PBGFSGD3ADPROT6L PBG.FSGD3ADPROT6.UINT16[L]
#define PBGFSGD3ADPROT6LL PBG.FSGD3ADPROT6.UINT8[LL]
#define PBGFSGD3ADPROT6LH PBG.FSGD3ADPROT6.UINT8[LH]
#define PBGFSGD3ADPROT6H PBG.FSGD3ADPROT6.UINT16[H]
#define PBGFSGD3ADPROT6HL PBG.FSGD3ADPROT6.UINT8[HL]
#define PBGFSGD3ADPROT6HH PBG.FSGD3ADPROT6.UINT8[HH]
#define PBGFSGD3ADPROT7 PBG.FSGD3ADPROT7.UINT32
#define PBGFSGD3ADPROT7L PBG.FSGD3ADPROT7.UINT16[L]
#define PBGFSGD3ADPROT7LL PBG.FSGD3ADPROT7.UINT8[LL]
#define PBGFSGD3ADPROT7LH PBG.FSGD3ADPROT7.UINT8[LH]
#define PBGFSGD3ADPROT7H PBG.FSGD3ADPROT7.UINT16[H]
#define PBGFSGD3ADPROT7HL PBG.FSGD3ADPROT7.UINT8[HL]
#define PBGFSGD3ADPROT7HH PBG.FSGD3ADPROT7.UINT8[HH]
#define PBGFSGD3ADPROT8 PBG.FSGD3ADPROT8.UINT32
#define PBGFSGD3ADPROT8L PBG.FSGD3ADPROT8.UINT16[L]
#define PBGFSGD3ADPROT8LL PBG.FSGD3ADPROT8.UINT8[LL]
#define PBGFSGD3ADPROT8LH PBG.FSGD3ADPROT8.UINT8[LH]
#define PBGFSGD3ADPROT8H PBG.FSGD3ADPROT8.UINT16[H]
#define PBGFSGD3ADPROT8HL PBG.FSGD3ADPROT8.UINT8[HL]
#define PBGFSGD3ADPROT8HH PBG.FSGD3ADPROT8.UINT8[HH]
#define PBGFSGD3ADPROT9 PBG.FSGD3ADPROT9.UINT32
#define PBGFSGD3ADPROT9L PBG.FSGD3ADPROT9.UINT16[L]
#define PBGFSGD3ADPROT9LL PBG.FSGD3ADPROT9.UINT8[LL]
#define PBGFSGD3ADPROT9LH PBG.FSGD3ADPROT9.UINT8[LH]
#define PBGFSGD3ADPROT9H PBG.FSGD3ADPROT9.UINT16[H]
#define PBGFSGD3ADPROT9HL PBG.FSGD3ADPROT9.UINT8[HL]
#define PBGFSGD3ADPROT9HH PBG.FSGD3ADPROT9.UINT8[HH]
#define PBGFSGD3ADPROT10 PBG.FSGD3ADPROT10.UINT32
#define PBGFSGD3ADPROT10L PBG.FSGD3ADPROT10.UINT16[L]
#define PBGFSGD3ADPROT10LL PBG.FSGD3ADPROT10.UINT8[LL]
#define PBGFSGD3ADPROT10LH PBG.FSGD3ADPROT10.UINT8[LH]
#define PBGFSGD3ADPROT10H PBG.FSGD3ADPROT10.UINT16[H]
#define PBGFSGD3ADPROT10HL PBG.FSGD3ADPROT10.UINT8[HL]
#define PBGFSGD3ADPROT10HH PBG.FSGD3ADPROT10.UINT8[HH]
#define PBGFSGD3ADPROT11 PBG.FSGD3ADPROT11.UINT32
#define PBGFSGD3ADPROT11L PBG.FSGD3ADPROT11.UINT16[L]
#define PBGFSGD3ADPROT11LL PBG.FSGD3ADPROT11.UINT8[LL]
#define PBGFSGD3ADPROT11LH PBG.FSGD3ADPROT11.UINT8[LH]
#define PBGFSGD3ADPROT11H PBG.FSGD3ADPROT11.UINT16[H]
#define PBGFSGD3ADPROT11HL PBG.FSGD3ADPROT11.UINT8[HL]
#define PBGFSGD3ADPROT11HH PBG.FSGD3ADPROT11.UINT8[HH]
#define PBGERRSLV3ACTL PBG.ERRSLV3ACTL.UINT32
#define PBGERRSLV3ACTLL PBG.ERRSLV3ACTL.UINT16[L]
#define PBGERRSLV3ACTLLL PBG.ERRSLV3ACTL.UINT8[LL]
#define PBGERRSLV3ACTLLH PBG.ERRSLV3ACTL.UINT8[LH]
#define PBGERRSLV3ACTLH PBG.ERRSLV3ACTL.UINT16[H]
#define PBGERRSLV3ACTLHL PBG.ERRSLV3ACTL.UINT8[HL]
#define PBGERRSLV3ACTLHH PBG.ERRSLV3ACTL.UINT8[HH]
#define PBGCLRE PBG.ERRSLV3ACTL.BIT.CLRE
#define PBGCLRO PBG.ERRSLV3ACTL.BIT.CLRO
#define PBGERRSLV3ASTAT PBG.ERRSLV3ASTAT.UINT32
#define PBGERRSLV3ASTATL PBG.ERRSLV3ASTAT.UINT16[L]
#define PBGERRSLV3ASTATLL PBG.ERRSLV3ASTAT.UINT8[LL]
#define PBGERRSLV3ASTATLH PBG.ERRSLV3ASTAT.UINT8[LH]
#define PBGERRSLV3ASTATH PBG.ERRSLV3ASTAT.UINT16[H]
#define PBGERRSLV3ASTATHL PBG.ERRSLV3ASTAT.UINT8[HL]
#define PBGERRSLV3ASTATHH PBG.ERRSLV3ASTAT.UINT8[HH]
#define PBGERR PBG.ERRSLV3ASTAT.BIT.ERR
#define PBGOVF PBG.ERRSLV3ASTAT.BIT.OVF
#define PBGERRSLV3AADDR PBG.ERRSLV3AADDR.UINT32
#define PBGADDR PBG.ERRSLV3AADDR.BIT.ADDR
#define PBGERRSLV3ATYPE PBG.ERRSLV3ATYPE.UINT32
#define PBGERRSLV3ATYPEL PBG.ERRSLV3ATYPE.UINT16[L]
#define PBGERRSLV3ATYPEH PBG.ERRSLV3ATYPE.UINT16[H]
#define PBGWRITE PBG.ERRSLV3ATYPE.BIT.WRITE
#define PBGSTRB PBG.ERRSLV3ATYPE.BIT.STRB
#define PBGUM PBG.ERRSLV3ATYPE.BIT.UM
#define PBGSPID PBG.ERRSLV3ATYPE.BIT.SPID
#define PBGPEID PBG.ERRSLV3ATYPE.BIT.PEID
#define PBGFSGD0ADPROT0 PBG.FSGD0ADPROT0.UINT32
#define PBGFSGD0ADPROT0L PBG.FSGD0ADPROT0.UINT16[L]
#define PBGFSGD0ADPROT0LL PBG.FSGD0ADPROT0.UINT8[LL]
#define PBGFSGD0ADPROT0LH PBG.FSGD0ADPROT0.UINT8[LH]
#define PBGFSGD0ADPROT0H PBG.FSGD0ADPROT0.UINT16[H]
#define PBGFSGD0ADPROT0HL PBG.FSGD0ADPROT0.UINT8[HL]
#define PBGFSGD0ADPROT0HH PBG.FSGD0ADPROT0.UINT8[HH]
#define PBGFSGD0ADPROT1 PBG.FSGD0ADPROT1.UINT32
#define PBGFSGD0ADPROT1L PBG.FSGD0ADPROT1.UINT16[L]
#define PBGFSGD0ADPROT1LL PBG.FSGD0ADPROT1.UINT8[LL]
#define PBGFSGD0ADPROT1LH PBG.FSGD0ADPROT1.UINT8[LH]
#define PBGFSGD0ADPROT1H PBG.FSGD0ADPROT1.UINT16[H]
#define PBGFSGD0ADPROT1HL PBG.FSGD0ADPROT1.UINT8[HL]
#define PBGFSGD0ADPROT1HH PBG.FSGD0ADPROT1.UINT8[HH]
#define PBGERRSLV0ACTL PBG.ERRSLV0ACTL.UINT32
#define PBGERRSLV0ACTLL PBG.ERRSLV0ACTL.UINT16[L]
#define PBGERRSLV0ACTLLL PBG.ERRSLV0ACTL.UINT8[LL]
#define PBGERRSLV0ACTLLH PBG.ERRSLV0ACTL.UINT8[LH]
#define PBGERRSLV0ACTLH PBG.ERRSLV0ACTL.UINT16[H]
#define PBGERRSLV0ACTLHL PBG.ERRSLV0ACTL.UINT8[HL]
#define PBGERRSLV0ACTLHH PBG.ERRSLV0ACTL.UINT8[HH]
#define PBGERRSLV0ASTAT PBG.ERRSLV0ASTAT.UINT32
#define PBGERRSLV0ASTATL PBG.ERRSLV0ASTAT.UINT16[L]
#define PBGERRSLV0ASTATLL PBG.ERRSLV0ASTAT.UINT8[LL]
#define PBGERRSLV0ASTATLH PBG.ERRSLV0ASTAT.UINT8[LH]
#define PBGERRSLV0ASTATH PBG.ERRSLV0ASTAT.UINT16[H]
#define PBGERRSLV0ASTATHL PBG.ERRSLV0ASTAT.UINT8[HL]
#define PBGERRSLV0ASTATHH PBG.ERRSLV0ASTAT.UINT8[HH]
#define PBGERRSLV0AADDR PBG.ERRSLV0AADDR.UINT32
#define PBGERRSLV0ATYPE PBG.ERRSLV0ATYPE.UINT32
#define PBGERRSLV0ATYPEL PBG.ERRSLV0ATYPE.UINT16[L]
#define PBGERRSLV0ATYPEH PBG.ERRSLV0ATYPE.UINT16[H]
#define PBGFSGD1ADPROT0 PBG.FSGD1ADPROT0.UINT32
#define PBGFSGD1ADPROT0L PBG.FSGD1ADPROT0.UINT16[L]
#define PBGFSGD1ADPROT0LL PBG.FSGD1ADPROT0.UINT8[LL]
#define PBGFSGD1ADPROT0LH PBG.FSGD1ADPROT0.UINT8[LH]
#define PBGFSGD1ADPROT0H PBG.FSGD1ADPROT0.UINT16[H]
#define PBGFSGD1ADPROT0HL PBG.FSGD1ADPROT0.UINT8[HL]
#define PBGFSGD1ADPROT0HH PBG.FSGD1ADPROT0.UINT8[HH]
#define PBGFSGD1ADPROT1 PBG.FSGD1ADPROT1.UINT32
#define PBGFSGD1ADPROT1L PBG.FSGD1ADPROT1.UINT16[L]
#define PBGFSGD1ADPROT1LL PBG.FSGD1ADPROT1.UINT8[LL]
#define PBGFSGD1ADPROT1LH PBG.FSGD1ADPROT1.UINT8[LH]
#define PBGFSGD1ADPROT1H PBG.FSGD1ADPROT1.UINT16[H]
#define PBGFSGD1ADPROT1HL PBG.FSGD1ADPROT1.UINT8[HL]
#define PBGFSGD1ADPROT1HH PBG.FSGD1ADPROT1.UINT8[HH]
#define PBGFSGD1ADPROT2 PBG.FSGD1ADPROT2.UINT32
#define PBGFSGD1ADPROT2L PBG.FSGD1ADPROT2.UINT16[L]
#define PBGFSGD1ADPROT2LL PBG.FSGD1ADPROT2.UINT8[LL]
#define PBGFSGD1ADPROT2LH PBG.FSGD1ADPROT2.UINT8[LH]
#define PBGFSGD1ADPROT2H PBG.FSGD1ADPROT2.UINT16[H]
#define PBGFSGD1ADPROT2HL PBG.FSGD1ADPROT2.UINT8[HL]
#define PBGFSGD1ADPROT2HH PBG.FSGD1ADPROT2.UINT8[HH]
#define PBGFSGD1ADPROT3 PBG.FSGD1ADPROT3.UINT32
#define PBGFSGD1ADPROT3L PBG.FSGD1ADPROT3.UINT16[L]
#define PBGFSGD1ADPROT3LL PBG.FSGD1ADPROT3.UINT8[LL]
#define PBGFSGD1ADPROT3LH PBG.FSGD1ADPROT3.UINT8[LH]
#define PBGFSGD1ADPROT3H PBG.FSGD1ADPROT3.UINT16[H]
#define PBGFSGD1ADPROT3HL PBG.FSGD1ADPROT3.UINT8[HL]
#define PBGFSGD1ADPROT3HH PBG.FSGD1ADPROT3.UINT8[HH]
#define PBGFSGD1ADPROT4 PBG.FSGD1ADPROT4.UINT32
#define PBGFSGD1ADPROT4L PBG.FSGD1ADPROT4.UINT16[L]
#define PBGFSGD1ADPROT4LL PBG.FSGD1ADPROT4.UINT8[LL]
#define PBGFSGD1ADPROT4LH PBG.FSGD1ADPROT4.UINT8[LH]
#define PBGFSGD1ADPROT4H PBG.FSGD1ADPROT4.UINT16[H]
#define PBGFSGD1ADPROT4HL PBG.FSGD1ADPROT4.UINT8[HL]
#define PBGFSGD1ADPROT4HH PBG.FSGD1ADPROT4.UINT8[HH]
#define PBGFSGD1ADPROT5 PBG.FSGD1ADPROT5.UINT32
#define PBGFSGD1ADPROT5L PBG.FSGD1ADPROT5.UINT16[L]
#define PBGFSGD1ADPROT5LL PBG.FSGD1ADPROT5.UINT8[LL]
#define PBGFSGD1ADPROT5LH PBG.FSGD1ADPROT5.UINT8[LH]
#define PBGFSGD1ADPROT5H PBG.FSGD1ADPROT5.UINT16[H]
#define PBGFSGD1ADPROT5HL PBG.FSGD1ADPROT5.UINT8[HL]
#define PBGFSGD1ADPROT5HH PBG.FSGD1ADPROT5.UINT8[HH]
#define PBGFSGD1ADPROT6 PBG.FSGD1ADPROT6.UINT32
#define PBGFSGD1ADPROT6L PBG.FSGD1ADPROT6.UINT16[L]
#define PBGFSGD1ADPROT6LL PBG.FSGD1ADPROT6.UINT8[LL]
#define PBGFSGD1ADPROT6LH PBG.FSGD1ADPROT6.UINT8[LH]
#define PBGFSGD1ADPROT6H PBG.FSGD1ADPROT6.UINT16[H]
#define PBGFSGD1ADPROT6HL PBG.FSGD1ADPROT6.UINT8[HL]
#define PBGFSGD1ADPROT6HH PBG.FSGD1ADPROT6.UINT8[HH]
#define PBGFSGD1ADPROT7 PBG.FSGD1ADPROT7.UINT32
#define PBGFSGD1ADPROT7L PBG.FSGD1ADPROT7.UINT16[L]
#define PBGFSGD1ADPROT7LL PBG.FSGD1ADPROT7.UINT8[LL]
#define PBGFSGD1ADPROT7LH PBG.FSGD1ADPROT7.UINT8[LH]
#define PBGFSGD1ADPROT7H PBG.FSGD1ADPROT7.UINT16[H]
#define PBGFSGD1ADPROT7HL PBG.FSGD1ADPROT7.UINT8[HL]
#define PBGFSGD1ADPROT7HH PBG.FSGD1ADPROT7.UINT8[HH]
#define PBGFSGD1ADPROT8 PBG.FSGD1ADPROT8.UINT32
#define PBGFSGD1ADPROT8L PBG.FSGD1ADPROT8.UINT16[L]
#define PBGFSGD1ADPROT8LL PBG.FSGD1ADPROT8.UINT8[LL]
#define PBGFSGD1ADPROT8LH PBG.FSGD1ADPROT8.UINT8[LH]
#define PBGFSGD1ADPROT8H PBG.FSGD1ADPROT8.UINT16[H]
#define PBGFSGD1ADPROT8HL PBG.FSGD1ADPROT8.UINT8[HL]
#define PBGFSGD1ADPROT8HH PBG.FSGD1ADPROT8.UINT8[HH]
#define PBGFSGD1ADPROT9 PBG.FSGD1ADPROT9.UINT32
#define PBGFSGD1ADPROT9L PBG.FSGD1ADPROT9.UINT16[L]
#define PBGFSGD1ADPROT9LL PBG.FSGD1ADPROT9.UINT8[LL]
#define PBGFSGD1ADPROT9LH PBG.FSGD1ADPROT9.UINT8[LH]
#define PBGFSGD1ADPROT9H PBG.FSGD1ADPROT9.UINT16[H]
#define PBGFSGD1ADPROT9HL PBG.FSGD1ADPROT9.UINT8[HL]
#define PBGFSGD1ADPROT9HH PBG.FSGD1ADPROT9.UINT8[HH]
#define PBGFSGD1ADPROT10 PBG.FSGD1ADPROT10.UINT32
#define PBGFSGD1ADPROT10L PBG.FSGD1ADPROT10.UINT16[L]
#define PBGFSGD1ADPROT10LL PBG.FSGD1ADPROT10.UINT8[LL]
#define PBGFSGD1ADPROT10LH PBG.FSGD1ADPROT10.UINT8[LH]
#define PBGFSGD1ADPROT10H PBG.FSGD1ADPROT10.UINT16[H]
#define PBGFSGD1ADPROT10HL PBG.FSGD1ADPROT10.UINT8[HL]
#define PBGFSGD1ADPROT10HH PBG.FSGD1ADPROT10.UINT8[HH]
#define PBGFSGD1ADPROT11 PBG.FSGD1ADPROT11.UINT32
#define PBGFSGD1ADPROT11L PBG.FSGD1ADPROT11.UINT16[L]
#define PBGFSGD1ADPROT11LL PBG.FSGD1ADPROT11.UINT8[LL]
#define PBGFSGD1ADPROT11LH PBG.FSGD1ADPROT11.UINT8[LH]
#define PBGFSGD1ADPROT11H PBG.FSGD1ADPROT11.UINT16[H]
#define PBGFSGD1ADPROT11HL PBG.FSGD1ADPROT11.UINT8[HL]
#define PBGFSGD1ADPROT11HH PBG.FSGD1ADPROT11.UINT8[HH]
#define PBGFSGD1ADPROT12 PBG.FSGD1ADPROT12.UINT32
#define PBGFSGD1ADPROT12L PBG.FSGD1ADPROT12.UINT16[L]
#define PBGFSGD1ADPROT12LL PBG.FSGD1ADPROT12.UINT8[LL]
#define PBGFSGD1ADPROT12LH PBG.FSGD1ADPROT12.UINT8[LH]
#define PBGFSGD1ADPROT12H PBG.FSGD1ADPROT12.UINT16[H]
#define PBGFSGD1ADPROT12HL PBG.FSGD1ADPROT12.UINT8[HL]
#define PBGFSGD1ADPROT12HH PBG.FSGD1ADPROT12.UINT8[HH]
#define PBGFSGD1ADPROT13 PBG.FSGD1ADPROT13.UINT32
#define PBGFSGD1ADPROT13L PBG.FSGD1ADPROT13.UINT16[L]
#define PBGFSGD1ADPROT13LL PBG.FSGD1ADPROT13.UINT8[LL]
#define PBGFSGD1ADPROT13LH PBG.FSGD1ADPROT13.UINT8[LH]
#define PBGFSGD1ADPROT13H PBG.FSGD1ADPROT13.UINT16[H]
#define PBGFSGD1ADPROT13HL PBG.FSGD1ADPROT13.UINT8[HL]
#define PBGFSGD1ADPROT13HH PBG.FSGD1ADPROT13.UINT8[HH]
#define PBGFSGD1ADPROT14 PBG.FSGD1ADPROT14.UINT32
#define PBGFSGD1ADPROT14L PBG.FSGD1ADPROT14.UINT16[L]
#define PBGFSGD1ADPROT14LL PBG.FSGD1ADPROT14.UINT8[LL]
#define PBGFSGD1ADPROT14LH PBG.FSGD1ADPROT14.UINT8[LH]
#define PBGFSGD1ADPROT14H PBG.FSGD1ADPROT14.UINT16[H]
#define PBGFSGD1ADPROT14HL PBG.FSGD1ADPROT14.UINT8[HL]
#define PBGFSGD1ADPROT14HH PBG.FSGD1ADPROT14.UINT8[HH]
#define PBGERRSLV1ACTL PBG.ERRSLV1ACTL.UINT32
#define PBGERRSLV1ACTLL PBG.ERRSLV1ACTL.UINT16[L]
#define PBGERRSLV1ACTLLL PBG.ERRSLV1ACTL.UINT8[LL]
#define PBGERRSLV1ACTLLH PBG.ERRSLV1ACTL.UINT8[LH]
#define PBGERRSLV1ACTLH PBG.ERRSLV1ACTL.UINT16[H]
#define PBGERRSLV1ACTLHL PBG.ERRSLV1ACTL.UINT8[HL]
#define PBGERRSLV1ACTLHH PBG.ERRSLV1ACTL.UINT8[HH]
#define PBGERRSLV1ASTAT PBG.ERRSLV1ASTAT.UINT32
#define PBGERRSLV1ASTATL PBG.ERRSLV1ASTAT.UINT16[L]
#define PBGERRSLV1ASTATLL PBG.ERRSLV1ASTAT.UINT8[LL]
#define PBGERRSLV1ASTATLH PBG.ERRSLV1ASTAT.UINT8[LH]
#define PBGERRSLV1ASTATH PBG.ERRSLV1ASTAT.UINT16[H]
#define PBGERRSLV1ASTATHL PBG.ERRSLV1ASTAT.UINT8[HL]
#define PBGERRSLV1ASTATHH PBG.ERRSLV1ASTAT.UINT8[HH]
#define PBGERRSLV1AADDR PBG.ERRSLV1AADDR.UINT32
#define PBGERRSLV1ATYPE PBG.ERRSLV1ATYPE.UINT32
#define PBGERRSLV1ATYPEL PBG.ERRSLV1ATYPE.UINT16[L]
#define PBGERRSLV1ATYPEH PBG.ERRSLV1ATYPE.UINT16[H]
#define PBGFSGD1BDPROT0 PBG.FSGD1BDPROT0.UINT32
#define PBGFSGD1BDPROT0L PBG.FSGD1BDPROT0.UINT16[L]
#define PBGFSGD1BDPROT0LL PBG.FSGD1BDPROT0.UINT8[LL]
#define PBGFSGD1BDPROT0LH PBG.FSGD1BDPROT0.UINT8[LH]
#define PBGFSGD1BDPROT0H PBG.FSGD1BDPROT0.UINT16[H]
#define PBGFSGD1BDPROT0HL PBG.FSGD1BDPROT0.UINT8[HL]
#define PBGFSGD1BDPROT0HH PBG.FSGD1BDPROT0.UINT8[HH]
#define PBGFSGD1BDPROT1 PBG.FSGD1BDPROT1.UINT32
#define PBGFSGD1BDPROT1L PBG.FSGD1BDPROT1.UINT16[L]
#define PBGFSGD1BDPROT1LL PBG.FSGD1BDPROT1.UINT8[LL]
#define PBGFSGD1BDPROT1LH PBG.FSGD1BDPROT1.UINT8[LH]
#define PBGFSGD1BDPROT1H PBG.FSGD1BDPROT1.UINT16[H]
#define PBGFSGD1BDPROT1HL PBG.FSGD1BDPROT1.UINT8[HL]
#define PBGFSGD1BDPROT1HH PBG.FSGD1BDPROT1.UINT8[HH]
#define PBGFSGD1BDPROT2 PBG.FSGD1BDPROT2.UINT32
#define PBGFSGD1BDPROT2L PBG.FSGD1BDPROT2.UINT16[L]
#define PBGFSGD1BDPROT2LL PBG.FSGD1BDPROT2.UINT8[LL]
#define PBGFSGD1BDPROT2LH PBG.FSGD1BDPROT2.UINT8[LH]
#define PBGFSGD1BDPROT2H PBG.FSGD1BDPROT2.UINT16[H]
#define PBGFSGD1BDPROT2HL PBG.FSGD1BDPROT2.UINT8[HL]
#define PBGFSGD1BDPROT2HH PBG.FSGD1BDPROT2.UINT8[HH]
#define PBGFSGD1BDPROT3 PBG.FSGD1BDPROT3.UINT32
#define PBGFSGD1BDPROT3L PBG.FSGD1BDPROT3.UINT16[L]
#define PBGFSGD1BDPROT3LL PBG.FSGD1BDPROT3.UINT8[LL]
#define PBGFSGD1BDPROT3LH PBG.FSGD1BDPROT3.UINT8[LH]
#define PBGFSGD1BDPROT3H PBG.FSGD1BDPROT3.UINT16[H]
#define PBGFSGD1BDPROT3HL PBG.FSGD1BDPROT3.UINT8[HL]
#define PBGFSGD1BDPROT3HH PBG.FSGD1BDPROT3.UINT8[HH]
#define PBGFSGD1BDPROT4 PBG.FSGD1BDPROT4.UINT32
#define PBGFSGD1BDPROT4L PBG.FSGD1BDPROT4.UINT16[L]
#define PBGFSGD1BDPROT4LL PBG.FSGD1BDPROT4.UINT8[LL]
#define PBGFSGD1BDPROT4LH PBG.FSGD1BDPROT4.UINT8[LH]
#define PBGFSGD1BDPROT4H PBG.FSGD1BDPROT4.UINT16[H]
#define PBGFSGD1BDPROT4HL PBG.FSGD1BDPROT4.UINT8[HL]
#define PBGFSGD1BDPROT4HH PBG.FSGD1BDPROT4.UINT8[HH]
#define PBGFSGD1BDPROT5 PBG.FSGD1BDPROT5.UINT32
#define PBGFSGD1BDPROT5L PBG.FSGD1BDPROT5.UINT16[L]
#define PBGFSGD1BDPROT5LL PBG.FSGD1BDPROT5.UINT8[LL]
#define PBGFSGD1BDPROT5LH PBG.FSGD1BDPROT5.UINT8[LH]
#define PBGFSGD1BDPROT5H PBG.FSGD1BDPROT5.UINT16[H]
#define PBGFSGD1BDPROT5HL PBG.FSGD1BDPROT5.UINT8[HL]
#define PBGFSGD1BDPROT5HH PBG.FSGD1BDPROT5.UINT8[HH]
#define PBGFSGD1BDPROT6 PBG.FSGD1BDPROT6.UINT32
#define PBGFSGD1BDPROT6L PBG.FSGD1BDPROT6.UINT16[L]
#define PBGFSGD1BDPROT6LL PBG.FSGD1BDPROT6.UINT8[LL]
#define PBGFSGD1BDPROT6LH PBG.FSGD1BDPROT6.UINT8[LH]
#define PBGFSGD1BDPROT6H PBG.FSGD1BDPROT6.UINT16[H]
#define PBGFSGD1BDPROT6HL PBG.FSGD1BDPROT6.UINT8[HL]
#define PBGFSGD1BDPROT6HH PBG.FSGD1BDPROT6.UINT8[HH]
#define PBGFSGD1BDPROT7 PBG.FSGD1BDPROT7.UINT32
#define PBGFSGD1BDPROT7L PBG.FSGD1BDPROT7.UINT16[L]
#define PBGFSGD1BDPROT7LL PBG.FSGD1BDPROT7.UINT8[LL]
#define PBGFSGD1BDPROT7LH PBG.FSGD1BDPROT7.UINT8[LH]
#define PBGFSGD1BDPROT7H PBG.FSGD1BDPROT7.UINT16[H]
#define PBGFSGD1BDPROT7HL PBG.FSGD1BDPROT7.UINT8[HL]
#define PBGFSGD1BDPROT7HH PBG.FSGD1BDPROT7.UINT8[HH]
#define PBGFSGD1BDPROT8 PBG.FSGD1BDPROT8.UINT32
#define PBGFSGD1BDPROT8L PBG.FSGD1BDPROT8.UINT16[L]
#define PBGFSGD1BDPROT8LL PBG.FSGD1BDPROT8.UINT8[LL]
#define PBGFSGD1BDPROT8LH PBG.FSGD1BDPROT8.UINT8[LH]
#define PBGFSGD1BDPROT8H PBG.FSGD1BDPROT8.UINT16[H]
#define PBGFSGD1BDPROT8HL PBG.FSGD1BDPROT8.UINT8[HL]
#define PBGFSGD1BDPROT8HH PBG.FSGD1BDPROT8.UINT8[HH]
#define PBGFSGD1BDPROT9 PBG.FSGD1BDPROT9.UINT32
#define PBGFSGD1BDPROT9L PBG.FSGD1BDPROT9.UINT16[L]
#define PBGFSGD1BDPROT9LL PBG.FSGD1BDPROT9.UINT8[LL]
#define PBGFSGD1BDPROT9LH PBG.FSGD1BDPROT9.UINT8[LH]
#define PBGFSGD1BDPROT9H PBG.FSGD1BDPROT9.UINT16[H]
#define PBGFSGD1BDPROT9HL PBG.FSGD1BDPROT9.UINT8[HL]
#define PBGFSGD1BDPROT9HH PBG.FSGD1BDPROT9.UINT8[HH]
#define PBGFSGD1BDPROT10 PBG.FSGD1BDPROT10.UINT32
#define PBGFSGD1BDPROT10L PBG.FSGD1BDPROT10.UINT16[L]
#define PBGFSGD1BDPROT10LL PBG.FSGD1BDPROT10.UINT8[LL]
#define PBGFSGD1BDPROT10LH PBG.FSGD1BDPROT10.UINT8[LH]
#define PBGFSGD1BDPROT10H PBG.FSGD1BDPROT10.UINT16[H]
#define PBGFSGD1BDPROT10HL PBG.FSGD1BDPROT10.UINT8[HL]
#define PBGFSGD1BDPROT10HH PBG.FSGD1BDPROT10.UINT8[HH]
#define PBGFSGD1BDPROT11 PBG.FSGD1BDPROT11.UINT32
#define PBGFSGD1BDPROT11L PBG.FSGD1BDPROT11.UINT16[L]
#define PBGFSGD1BDPROT11LL PBG.FSGD1BDPROT11.UINT8[LL]
#define PBGFSGD1BDPROT11LH PBG.FSGD1BDPROT11.UINT8[LH]
#define PBGFSGD1BDPROT11H PBG.FSGD1BDPROT11.UINT16[H]
#define PBGFSGD1BDPROT11HL PBG.FSGD1BDPROT11.UINT8[HL]
#define PBGFSGD1BDPROT11HH PBG.FSGD1BDPROT11.UINT8[HH]
#define PBGFSGD1BDPROT12 PBG.FSGD1BDPROT12.UINT32
#define PBGFSGD1BDPROT12L PBG.FSGD1BDPROT12.UINT16[L]
#define PBGFSGD1BDPROT12LL PBG.FSGD1BDPROT12.UINT8[LL]
#define PBGFSGD1BDPROT12LH PBG.FSGD1BDPROT12.UINT8[LH]
#define PBGFSGD1BDPROT12H PBG.FSGD1BDPROT12.UINT16[H]
#define PBGFSGD1BDPROT12HL PBG.FSGD1BDPROT12.UINT8[HL]
#define PBGFSGD1BDPROT12HH PBG.FSGD1BDPROT12.UINT8[HH]
#define PBGFSGD1BDPROT13 PBG.FSGD1BDPROT13.UINT32
#define PBGFSGD1BDPROT13L PBG.FSGD1BDPROT13.UINT16[L]
#define PBGFSGD1BDPROT13LL PBG.FSGD1BDPROT13.UINT8[LL]
#define PBGFSGD1BDPROT13LH PBG.FSGD1BDPROT13.UINT8[LH]
#define PBGFSGD1BDPROT13H PBG.FSGD1BDPROT13.UINT16[H]
#define PBGFSGD1BDPROT13HL PBG.FSGD1BDPROT13.UINT8[HL]
#define PBGFSGD1BDPROT13HH PBG.FSGD1BDPROT13.UINT8[HH]
#define PBGFSGD1BDPROT14 PBG.FSGD1BDPROT14.UINT32
#define PBGFSGD1BDPROT14L PBG.FSGD1BDPROT14.UINT16[L]
#define PBGFSGD1BDPROT14LL PBG.FSGD1BDPROT14.UINT8[LL]
#define PBGFSGD1BDPROT14LH PBG.FSGD1BDPROT14.UINT8[LH]
#define PBGFSGD1BDPROT14H PBG.FSGD1BDPROT14.UINT16[H]
#define PBGFSGD1BDPROT14HL PBG.FSGD1BDPROT14.UINT8[HL]
#define PBGFSGD1BDPROT14HH PBG.FSGD1BDPROT14.UINT8[HH]
#define PBGERRSLV1BCTL PBG.ERRSLV1BCTL.UINT32
#define PBGERRSLV1BCTLL PBG.ERRSLV1BCTL.UINT16[L]
#define PBGERRSLV1BCTLLL PBG.ERRSLV1BCTL.UINT8[LL]
#define PBGERRSLV1BCTLLH PBG.ERRSLV1BCTL.UINT8[LH]
#define PBGERRSLV1BCTLH PBG.ERRSLV1BCTL.UINT16[H]
#define PBGERRSLV1BCTLHL PBG.ERRSLV1BCTL.UINT8[HL]
#define PBGERRSLV1BCTLHH PBG.ERRSLV1BCTL.UINT8[HH]
#define PBGERRSLV1BSTAT PBG.ERRSLV1BSTAT.UINT32
#define PBGERRSLV1BSTATL PBG.ERRSLV1BSTAT.UINT16[L]
#define PBGERRSLV1BSTATLL PBG.ERRSLV1BSTAT.UINT8[LL]
#define PBGERRSLV1BSTATLH PBG.ERRSLV1BSTAT.UINT8[LH]
#define PBGERRSLV1BSTATH PBG.ERRSLV1BSTAT.UINT16[H]
#define PBGERRSLV1BSTATHL PBG.ERRSLV1BSTAT.UINT8[HL]
#define PBGERRSLV1BSTATHH PBG.ERRSLV1BSTAT.UINT8[HH]
#define PBGERRSLV1BADDR PBG.ERRSLV1BADDR.UINT32
#define PBGERRSLV1BTYPE PBG.ERRSLV1BTYPE.UINT32
#define PBGERRSLV1BTYPEL PBG.ERRSLV1BTYPE.UINT16[L]
#define PBGERRSLV1BTYPEH PBG.ERRSLV1BTYPE.UINT16[H]
#define PBGFSGD5ADPROT0 PBG.FSGD5ADPROT0.UINT32
#define PBGFSGD5ADPROT0L PBG.FSGD5ADPROT0.UINT16[L]
#define PBGFSGD5ADPROT0LL PBG.FSGD5ADPROT0.UINT8[LL]
#define PBGFSGD5ADPROT0LH PBG.FSGD5ADPROT0.UINT8[LH]
#define PBGFSGD5ADPROT0H PBG.FSGD5ADPROT0.UINT16[H]
#define PBGFSGD5ADPROT0HL PBG.FSGD5ADPROT0.UINT8[HL]
#define PBGFSGD5ADPROT0HH PBG.FSGD5ADPROT0.UINT8[HH]
#define PBGERRSLV5ACTL PBG.ERRSLV5ACTL.UINT32
#define PBGERRSLV5ACTLL PBG.ERRSLV5ACTL.UINT16[L]
#define PBGERRSLV5ACTLLL PBG.ERRSLV5ACTL.UINT8[LL]
#define PBGERRSLV5ACTLLH PBG.ERRSLV5ACTL.UINT8[LH]
#define PBGERRSLV5ACTLH PBG.ERRSLV5ACTL.UINT16[H]
#define PBGERRSLV5ACTLHL PBG.ERRSLV5ACTL.UINT8[HL]
#define PBGERRSLV5ACTLHH PBG.ERRSLV5ACTL.UINT8[HH]
#define PBGERRSLV5ASTAT PBG.ERRSLV5ASTAT.UINT32
#define PBGERRSLV5ASTATL PBG.ERRSLV5ASTAT.UINT16[L]
#define PBGERRSLV5ASTATLL PBG.ERRSLV5ASTAT.UINT8[LL]
#define PBGERRSLV5ASTATLH PBG.ERRSLV5ASTAT.UINT8[LH]
#define PBGERRSLV5ASTATH PBG.ERRSLV5ASTAT.UINT16[H]
#define PBGERRSLV5ASTATHL PBG.ERRSLV5ASTAT.UINT8[HL]
#define PBGERRSLV5ASTATHH PBG.ERRSLV5ASTAT.UINT8[HH]
#define PBGERRSLV5AADDR PBG.ERRSLV5AADDR.UINT32
#define PBGERRSLV5ATYPE PBG.ERRSLV5ATYPE.UINT32
#define PBGERRSLV5ATYPEL PBG.ERRSLV5ATYPE.UINT16[L]
#define PBGERRSLV5ATYPEH PBG.ERRSLV5ATYPE.UINT16[H]
#define PBGFSGD2ADPROT0 PBG.FSGD2ADPROT0.UINT32
#define PBGFSGD2ADPROT0L PBG.FSGD2ADPROT0.UINT16[L]
#define PBGFSGD2ADPROT0LL PBG.FSGD2ADPROT0.UINT8[LL]
#define PBGFSGD2ADPROT0LH PBG.FSGD2ADPROT0.UINT8[LH]
#define PBGFSGD2ADPROT0H PBG.FSGD2ADPROT0.UINT16[H]
#define PBGFSGD2ADPROT0HL PBG.FSGD2ADPROT0.UINT8[HL]
#define PBGFSGD2ADPROT0HH PBG.FSGD2ADPROT0.UINT8[HH]
#define PBGFSGD2ADPROT1 PBG.FSGD2ADPROT1.UINT32
#define PBGFSGD2ADPROT1L PBG.FSGD2ADPROT1.UINT16[L]
#define PBGFSGD2ADPROT1LL PBG.FSGD2ADPROT1.UINT8[LL]
#define PBGFSGD2ADPROT1LH PBG.FSGD2ADPROT1.UINT8[LH]
#define PBGFSGD2ADPROT1H PBG.FSGD2ADPROT1.UINT16[H]
#define PBGFSGD2ADPROT1HL PBG.FSGD2ADPROT1.UINT8[HL]
#define PBGFSGD2ADPROT1HH PBG.FSGD2ADPROT1.UINT8[HH]
#define PBGFSGD2ADPROT2 PBG.FSGD2ADPROT2.UINT32
#define PBGFSGD2ADPROT2L PBG.FSGD2ADPROT2.UINT16[L]
#define PBGFSGD2ADPROT2LL PBG.FSGD2ADPROT2.UINT8[LL]
#define PBGFSGD2ADPROT2LH PBG.FSGD2ADPROT2.UINT8[LH]
#define PBGFSGD2ADPROT2H PBG.FSGD2ADPROT2.UINT16[H]
#define PBGFSGD2ADPROT2HL PBG.FSGD2ADPROT2.UINT8[HL]
#define PBGFSGD2ADPROT2HH PBG.FSGD2ADPROT2.UINT8[HH]
#define PBGFSGD2ADPROT3 PBG.FSGD2ADPROT3.UINT32
#define PBGFSGD2ADPROT3L PBG.FSGD2ADPROT3.UINT16[L]
#define PBGFSGD2ADPROT3LL PBG.FSGD2ADPROT3.UINT8[LL]
#define PBGFSGD2ADPROT3LH PBG.FSGD2ADPROT3.UINT8[LH]
#define PBGFSGD2ADPROT3H PBG.FSGD2ADPROT3.UINT16[H]
#define PBGFSGD2ADPROT3HL PBG.FSGD2ADPROT3.UINT8[HL]
#define PBGFSGD2ADPROT3HH PBG.FSGD2ADPROT3.UINT8[HH]
#define PBGFSGD2ADPROT4 PBG.FSGD2ADPROT4.UINT32
#define PBGFSGD2ADPROT4L PBG.FSGD2ADPROT4.UINT16[L]
#define PBGFSGD2ADPROT4LL PBG.FSGD2ADPROT4.UINT8[LL]
#define PBGFSGD2ADPROT4LH PBG.FSGD2ADPROT4.UINT8[LH]
#define PBGFSGD2ADPROT4H PBG.FSGD2ADPROT4.UINT16[H]
#define PBGFSGD2ADPROT4HL PBG.FSGD2ADPROT4.UINT8[HL]
#define PBGFSGD2ADPROT4HH PBG.FSGD2ADPROT4.UINT8[HH]
#define PBGFSGD2ADPROT5 PBG.FSGD2ADPROT5.UINT32
#define PBGFSGD2ADPROT5L PBG.FSGD2ADPROT5.UINT16[L]
#define PBGFSGD2ADPROT5LL PBG.FSGD2ADPROT5.UINT8[LL]
#define PBGFSGD2ADPROT5LH PBG.FSGD2ADPROT5.UINT8[LH]
#define PBGFSGD2ADPROT5H PBG.FSGD2ADPROT5.UINT16[H]
#define PBGFSGD2ADPROT5HL PBG.FSGD2ADPROT5.UINT8[HL]
#define PBGFSGD2ADPROT5HH PBG.FSGD2ADPROT5.UINT8[HH]
#define PBGFSGD2ADPROT6 PBG.FSGD2ADPROT6.UINT32
#define PBGFSGD2ADPROT6L PBG.FSGD2ADPROT6.UINT16[L]
#define PBGFSGD2ADPROT6LL PBG.FSGD2ADPROT6.UINT8[LL]
#define PBGFSGD2ADPROT6LH PBG.FSGD2ADPROT6.UINT8[LH]
#define PBGFSGD2ADPROT6H PBG.FSGD2ADPROT6.UINT16[H]
#define PBGFSGD2ADPROT6HL PBG.FSGD2ADPROT6.UINT8[HL]
#define PBGFSGD2ADPROT6HH PBG.FSGD2ADPROT6.UINT8[HH]
#define PBGFSGD2ADPROT7 PBG.FSGD2ADPROT7.UINT32
#define PBGFSGD2ADPROT7L PBG.FSGD2ADPROT7.UINT16[L]
#define PBGFSGD2ADPROT7LL PBG.FSGD2ADPROT7.UINT8[LL]
#define PBGFSGD2ADPROT7LH PBG.FSGD2ADPROT7.UINT8[LH]
#define PBGFSGD2ADPROT7H PBG.FSGD2ADPROT7.UINT16[H]
#define PBGFSGD2ADPROT7HL PBG.FSGD2ADPROT7.UINT8[HL]
#define PBGFSGD2ADPROT7HH PBG.FSGD2ADPROT7.UINT8[HH]
#define PBGFSGD2ADPROT8 PBG.FSGD2ADPROT8.UINT32
#define PBGFSGD2ADPROT8L PBG.FSGD2ADPROT8.UINT16[L]
#define PBGFSGD2ADPROT8LL PBG.FSGD2ADPROT8.UINT8[LL]
#define PBGFSGD2ADPROT8LH PBG.FSGD2ADPROT8.UINT8[LH]
#define PBGFSGD2ADPROT8H PBG.FSGD2ADPROT8.UINT16[H]
#define PBGFSGD2ADPROT8HL PBG.FSGD2ADPROT8.UINT8[HL]
#define PBGFSGD2ADPROT8HH PBG.FSGD2ADPROT8.UINT8[HH]
#define PBGFSGD2ADPROT9 PBG.FSGD2ADPROT9.UINT32
#define PBGFSGD2ADPROT9L PBG.FSGD2ADPROT9.UINT16[L]
#define PBGFSGD2ADPROT9LL PBG.FSGD2ADPROT9.UINT8[LL]
#define PBGFSGD2ADPROT9LH PBG.FSGD2ADPROT9.UINT8[LH]
#define PBGFSGD2ADPROT9H PBG.FSGD2ADPROT9.UINT16[H]
#define PBGFSGD2ADPROT9HL PBG.FSGD2ADPROT9.UINT8[HL]
#define PBGFSGD2ADPROT9HH PBG.FSGD2ADPROT9.UINT8[HH]
#define PBGFSGD2ADPROT10 PBG.FSGD2ADPROT10.UINT32
#define PBGFSGD2ADPROT10L PBG.FSGD2ADPROT10.UINT16[L]
#define PBGFSGD2ADPROT10LL PBG.FSGD2ADPROT10.UINT8[LL]
#define PBGFSGD2ADPROT10LH PBG.FSGD2ADPROT10.UINT8[LH]
#define PBGFSGD2ADPROT10H PBG.FSGD2ADPROT10.UINT16[H]
#define PBGFSGD2ADPROT10HL PBG.FSGD2ADPROT10.UINT8[HL]
#define PBGFSGD2ADPROT10HH PBG.FSGD2ADPROT10.UINT8[HH]
#define PBGFSGD2ADPROT11 PBG.FSGD2ADPROT11.UINT32
#define PBGFSGD2ADPROT11L PBG.FSGD2ADPROT11.UINT16[L]
#define PBGFSGD2ADPROT11LL PBG.FSGD2ADPROT11.UINT8[LL]
#define PBGFSGD2ADPROT11LH PBG.FSGD2ADPROT11.UINT8[LH]
#define PBGFSGD2ADPROT11H PBG.FSGD2ADPROT11.UINT16[H]
#define PBGFSGD2ADPROT11HL PBG.FSGD2ADPROT11.UINT8[HL]
#define PBGFSGD2ADPROT11HH PBG.FSGD2ADPROT11.UINT8[HH]
#define PBGFSGD2ADPROT12 PBG.FSGD2ADPROT12.UINT32
#define PBGFSGD2ADPROT12L PBG.FSGD2ADPROT12.UINT16[L]
#define PBGFSGD2ADPROT12LL PBG.FSGD2ADPROT12.UINT8[LL]
#define PBGFSGD2ADPROT12LH PBG.FSGD2ADPROT12.UINT8[LH]
#define PBGFSGD2ADPROT12H PBG.FSGD2ADPROT12.UINT16[H]
#define PBGFSGD2ADPROT12HL PBG.FSGD2ADPROT12.UINT8[HL]
#define PBGFSGD2ADPROT12HH PBG.FSGD2ADPROT12.UINT8[HH]
#define PBGFSGD2ADPROT13 PBG.FSGD2ADPROT13.UINT32
#define PBGFSGD2ADPROT13L PBG.FSGD2ADPROT13.UINT16[L]
#define PBGFSGD2ADPROT13LL PBG.FSGD2ADPROT13.UINT8[LL]
#define PBGFSGD2ADPROT13LH PBG.FSGD2ADPROT13.UINT8[LH]
#define PBGFSGD2ADPROT13H PBG.FSGD2ADPROT13.UINT16[H]
#define PBGFSGD2ADPROT13HL PBG.FSGD2ADPROT13.UINT8[HL]
#define PBGFSGD2ADPROT13HH PBG.FSGD2ADPROT13.UINT8[HH]
#define PBGFSGD2ADPROT14 PBG.FSGD2ADPROT14.UINT32
#define PBGFSGD2ADPROT14L PBG.FSGD2ADPROT14.UINT16[L]
#define PBGFSGD2ADPROT14LL PBG.FSGD2ADPROT14.UINT8[LL]
#define PBGFSGD2ADPROT14LH PBG.FSGD2ADPROT14.UINT8[LH]
#define PBGFSGD2ADPROT14H PBG.FSGD2ADPROT14.UINT16[H]
#define PBGFSGD2ADPROT14HL PBG.FSGD2ADPROT14.UINT8[HL]
#define PBGFSGD2ADPROT14HH PBG.FSGD2ADPROT14.UINT8[HH]
#define PBGFSGD2ADPROT15 PBG.FSGD2ADPROT15.UINT32
#define PBGFSGD2ADPROT15L PBG.FSGD2ADPROT15.UINT16[L]
#define PBGFSGD2ADPROT15LL PBG.FSGD2ADPROT15.UINT8[LL]
#define PBGFSGD2ADPROT15LH PBG.FSGD2ADPROT15.UINT8[LH]
#define PBGFSGD2ADPROT15H PBG.FSGD2ADPROT15.UINT16[H]
#define PBGFSGD2ADPROT15HL PBG.FSGD2ADPROT15.UINT8[HL]
#define PBGFSGD2ADPROT15HH PBG.FSGD2ADPROT15.UINT8[HH]
#define PBGERRSLV2ACTL PBG.ERRSLV2ACTL.UINT32
#define PBGERRSLV2ACTLL PBG.ERRSLV2ACTL.UINT16[L]
#define PBGERRSLV2ACTLLL PBG.ERRSLV2ACTL.UINT8[LL]
#define PBGERRSLV2ACTLLH PBG.ERRSLV2ACTL.UINT8[LH]
#define PBGERRSLV2ACTLH PBG.ERRSLV2ACTL.UINT16[H]
#define PBGERRSLV2ACTLHL PBG.ERRSLV2ACTL.UINT8[HL]
#define PBGERRSLV2ACTLHH PBG.ERRSLV2ACTL.UINT8[HH]
#define PBGERRSLV2ASTAT PBG.ERRSLV2ASTAT.UINT32
#define PBGERRSLV2ASTATL PBG.ERRSLV2ASTAT.UINT16[L]
#define PBGERRSLV2ASTATLL PBG.ERRSLV2ASTAT.UINT8[LL]
#define PBGERRSLV2ASTATLH PBG.ERRSLV2ASTAT.UINT8[LH]
#define PBGERRSLV2ASTATH PBG.ERRSLV2ASTAT.UINT16[H]
#define PBGERRSLV2ASTATHL PBG.ERRSLV2ASTAT.UINT8[HL]
#define PBGERRSLV2ASTATHH PBG.ERRSLV2ASTAT.UINT8[HH]
#define PBGERRSLV2AADDR PBG.ERRSLV2AADDR.UINT32
#define PBGERRSLV2ATYPE PBG.ERRSLV2ATYPE.UINT32
#define PBGERRSLV2ATYPEL PBG.ERRSLV2ATYPE.UINT16[L]
#define PBGERRSLV2ATYPEH PBG.ERRSLV2ATYPE.UINT16[H]

#endif
