/**********************************************************************************************************************
* Copyright 2015, 2016 Nxtr 
* Nxtr Confidential
*
* Module File Name:   CDD_NvMProxyApi.c
* Module Description: Implementation of NvM Proxy ES006A
* Project           : CBD 
* Author            : Kevin Smith
***********************************************************************************************************************
* Version Control:
* %version:          2 %
* %derived_by:       cz7lt6 %
*----------------------------------------------------------------------------------------------------------------------
* Date      Rev      Author         Change Description                                                           SCR #
* -------   -------  --------  ---------------------------------------------------------------------------     --------
* 05/01/15  1        KJS       Initial Version                                                                 EA4#471
* 01/27/16  2        KJS       Updated file for EA4 naming and coding standards                                EA4#3443
**********************************************************************************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << Start of include and declaration area >>        DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/
#include "Rte_CDD_NvMProxy.h"
#include "CDD_NvMProxy_Cfg_private.h"
#include "NvM.h"
#include "Os.h"
#include "CDD_NvMProxy.h" /* Required to be included after NvM.h and Os.h */

/******************************************** File Level Rule Deviations *********************************************/
/* MISRA-C:2004 Rule 11.4 [NXTRDEV 11.4.4]: Cast of a variable pointer to void, to a pointer of a structure type for 
                                            passing parameters to non-trusted functions. */
/* MISRA-C:2004 Rule 16.7 [NXTRDEV 16.7.1]: Const is not used due to limitation of function arguments generated by Developer. */
/* MISRA-C:2004 Rule 19.1 [NXTRDEV 19.1.1]: AUTOSAR requires deviation from this rule for Memory Mapping include statements */

/********************************************* Embedded Local Constants **********************************************/

/******************************************* Module Specific Data Types **********************************************/
/* The following elements in the structures do not follow Nxtr's EA4 naming conventions. To help with readability 
   of the code the structure members were designed to follow the same argument names as the NvM API defined by AUTOSAR.*/

typedef struct {
    NvM_BlockIdType BlockId;
} NtEraseNvBlockRec;

typedef struct {
    NvM_BlockIdType BlockId;
    uint8*          RequestResultPtr;
} NtGetErrorStatusRec;

typedef struct {
    NvM_BlockIdType BlockId;
    uint8*          DataIndexPtr;
} NtGetDataIndexRec;

/* InvalidateNvBlock has the same arguments as EraseNvBlock, create a typedef with the same struct */
typedef NtEraseNvBlockRec NtInvalidateNvBlockRec;

typedef struct {
    NvM_BlockIdType BlockId;
    uint8*          NvM_DstPtr;
} NtReadBlockRec;

/* RestoreBlockDefaults has the same arguments as ReadBlock, create a typedef with the same struct */
typedef NtReadBlockRec NtRestoreBlockDefaultsRec;

typedef struct {
    NvM_BlockIdType BlockId;
    boolean         ProtectionEnabled;
} NtSetBlockProtectionRec;

typedef struct {
    NvM_BlockIdType BlockId;
    uint8           DataIndex;
} NtSetDataIndexRec;

typedef struct {
    NvM_BlockIdType BlockId;
    boolean         BlockChanged;
} NtSetRamBlockStatusRec;

typedef struct {
    NvM_BlockIdType BlockId;
    const uint8*    NvM_SrcPtr;
} NtWriteBlockRec;


/******************************************** Module Specific Variables **********************************************/

/******************************************** Local Function Prototypes **********************************************/

/*********************************************** Function Definitions ************************************************/

/**********************************************************************************************************************
 * DO NOT CHANGE THIS COMMENT!           << End of include and declaration area >>          DO NOT CHANGE THIS COMMENT!
 *********************************************************************************************************************/

#define CDD_NvMProxy_START_SEC_CODE
#include "CDD_NvMProxy_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* The following function arguments in the functions below do not follow Nxtr's EA4 naming conventions. 
   To help with readability of the code the function arguments were designed to follow the same argument names as the 
   NvM API defined by AUTOSAR.*/

/**********************************************************************************************************************
* Name:        NvMProxy_EraseNvBlock
*
* Description: Reads the block dependent error/status information and returns the result to the pointer
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_EraseNvBlock( NvM_BlockIdType BlockId )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtEraseNvBlockRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_EraseNvBlock( BlockId );
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_EraseNvBlock, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_GetDataIndex
*
* Description: The request passes the current DataIndex (association) of the specified dataset block.
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              DataIndexPtr - Address where the current DataIndex shall be written to
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_GetDataIndex( NvM_BlockIdType BlockId,
                                                               P2VAR(uint8, AUTOMATIC, AUTOMATIC) DataIndexPtr )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtGetDataIndexRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_GetDataIndex( BlockId, DataIndexPtr );
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_GetDataIndex, &Prm_Cnt_T_str);

        *DataIndexPtr = Rte_Pim_CmdRtnBuf()[BlockId].ReqRes;
        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_GetErrorStatus
*
* Description: Reads the block dependent error/status information and returns the result to the pointer
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              RequestResultPtr - Address to write the error status for the provided NvM block index
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_GetErrorStatus( NvM_BlockIdType BlockId, 
                                                                 P2VAR(uint8, AUTOMATIC, AUTOMATIC) RequestResultPtr )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtGetErrorStatusRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_GetErrorStatus(BlockId, RequestResultPtr);
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_GetErrorStatus, &Prm_Cnt_T_str);

        *RequestResultPtr = Rte_Pim_CmdRtnBuf()[BlockId].ReqRes;
        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_InvalidateNvBlock
*
* Description: Invalidates the specified NvM block, performs the same operation as NvMProxy_EraseBlock
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_InvalidateNvBlock( NvM_BlockIdType BlockId )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtInvalidateNvBlockRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_InvalidateNvBlock( BlockId );
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_InvalidateNvBlock, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_ReadBlock
*
* Description: Request to copy the data of the NV block to its corresponding RAM block
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              NvM_DstPtr - Pointer where the data of a non-permanent RAM shall be written to. If NULL_PTR is passed
*                           the data will be written to the permanent address configured in NvM.
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_ReadBlock( NvM_BlockIdType BlockId,
                                                            P2VAR(uint8, AUTOMATIC, AUTOMATIC) NvM_DstPtr )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtReadBlockRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_ReadBlock(BlockId, NvM_DstPtr);
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        Prm_Cnt_T_str.NvM_DstPtr = NvM_DstPtr;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_WriteBlock, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }
    
    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_RestoreBlockDefaults
*
* Description: Request to copy ROM defaults into the RAM shadow.
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              NvM_DstPtr - Pointer where the data of a non-permanent RAM shall be written to. If NULL_PTR is passed
*                           the data will be written to the permanent address configured in NvM.
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: Function currently is not supported in this version. Stub however was required based on NvM component.
*              Function will always return E_NOT_OK until function is defined.
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_RestoreBlockDefaults( NvM_BlockIdType BlockId,
                                                                       P2VAR(uint8, AUTOMATIC, AUTOMATIC) NvM_DstPtr )
{

    return E_NOT_OK;
}

/**********************************************************************************************************************
* Name:        NvMProxy_SetBlockProtection
*
* Description: Sets the write protection for the NV Block. Any further write, erase, or invalidate requests to the
*              NVRAM block will be rejected.
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              ProtectionEnabled - True: Enable Protection. False: Disable Protection.
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_SetBlockProtection( NvM_BlockIdType BlockId,
                                                                     VAR(boolean, AUTOMATIC) ProtectionEnabled )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtSetBlockProtectionRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_SetBlockProtection(BlockId, ProtectionEnabled);
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        Prm_Cnt_T_str.ProtectionEnabled = ProtectionEnabled;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_SetBlockProtection, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_SetDataIndex
*
* Description: The request passes the current DataIndex (association) of the specified dataset block.
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              DataIndexPtr - Address where the current DataIndex shall be written to
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_SetDataIndex( NvM_BlockIdType BlockId,
                                                               VAR(uint8, AUTOMATIC) DataIndex )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtSetDataIndexRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_SetDataIndex( BlockId, DataIndex );
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        Prm_Cnt_T_str.DataIndex = DataIndex;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_SetDataIndex, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_SetRamBlockStatus
*
* Description: Request to copy the data of the NV block to its corresponding RAM block
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              BlockChanged - True: Indicates block changed. False: Mark the block as unchanged
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_SetRamBlockStatus( NvM_BlockIdType BlockId,
                                                                    VAR(boolean, AUTOMATIC) BlockChanged )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtSetRamBlockStatusRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_SetRamBlockStatus(BlockId, BlockChanged);
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        Prm_Cnt_T_str.BlockChanged = BlockChanged;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_SetRamBlockStatus, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }

    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* Name:        NvMProxy_WriteBlock
*
* Description: Request to write the data of the RAM block to its corresponding NV block
*
* Inputs:      BlockId - NvM Block index on which to perform the operation
*              NvM_SrcPtr - Pointer where the data of a non-permanent RAM shall be read from. If NULL_PTR is passed
*                           the data will be read to the permanent address configured in NvM.
*
* Outputs:     Std_ReturnType (E_OK/E_NOT_OK)
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(Std_ReturnType, CDD_NvMProxy_CODE) NvMProxy_WriteBlock( NvM_BlockIdType BlockId,
                                                             P2CONST(uint8, AUTOMATIC, AUTOMATIC) NvM_SrcPtr )
{
    /* Local Variables */
    VAR(Std_ReturnType, AUTOMATIC) RtnVal_Cnt_T_u08;
    VAR(NtWriteBlockRec, AUTOMATIC) Prm_Cnt_T_str;
    
    if ( NVMOSAPP_CNT_U08 == GetApplicationID() )
    {
        /* Caller is in the same application as NvM, no context switch required */
        RtnVal_Cnt_T_u08 = NvM_WriteBlock(BlockId, NvM_SrcPtr);
    }
    else
    {
        /* Caller is not in the same application as NvM, context switch required */
        Prm_Cnt_T_str.BlockId = BlockId;
        Prm_Cnt_T_str.NvM_SrcPtr = NvM_SrcPtr;
        (void)CallNonTrustedFunction((NonTrustedFunctionIndexType)NtWrapS_NvM_WriteBlock, &Prm_Cnt_T_str);

        RtnVal_Cnt_T_u08 = Rte_Pim_CmdRtnBuf()[BlockId].StdRtn;
    }
    
    return RtnVal_Cnt_T_u08;
}

/**********************************************************************************************************************
* NvM Proxy Non-Trusted Function Definitions
**********************************************************************************************************************/

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_EraseNvBlock
*
* Description: Non-trusted function call for NvM_EraseNvBlock
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_EraseNvBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtEraseNvBlockRec*)FunctionParams)->BlockId].StdRtn = NvM_EraseNvBlock( ((NtEraseNvBlockRec*)FunctionParams)->BlockId );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_GetErrorStatus
*
* Description: Non-trusted function call for NvM_GetErrorStatus
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_GetErrorStatus(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtGetErrorStatusRec*)FunctionParams)->BlockId].StdRtn = NvM_GetErrorStatus( ((NtGetErrorStatusRec*)FunctionParams)->BlockId,
                                                                                                      &Rte_Pim_CmdRtnBuf()[((NtGetErrorStatusRec*)FunctionParams)->BlockId].ReqRes );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_InvalidateNvBlock
*
* Description: Non-trusted function call for NvM_InvalidateNvBlock
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_InvalidateNvBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtInvalidateNvBlockRec*)FunctionParams)->BlockId].StdRtn = NvM_InvalidateNvBlock( ((NtInvalidateNvBlockRec*)FunctionParams)->BlockId );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_ReadBlock
*
* Description: Non-trusted function call for NvM_ReadBlock
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_ReadBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtReadBlockRec*)FunctionParams)->BlockId].StdRtn = NvM_ReadBlock( ((NtReadBlockRec*)FunctionParams)->BlockId,
                                                                                            ((NtReadBlockRec*)FunctionParams)->NvM_DstPtr );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_SetBlockProtection
*
* Description: Non-trusted function call for NvM_SetBlockProtection
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_SetBlockProtection(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtSetBlockProtectionRec*)FunctionParams)->BlockId].StdRtn = NvM_SetBlockProtection( ((NtSetBlockProtectionRec*)FunctionParams)->BlockId,
                                                                                                              ((NtSetBlockProtectionRec*)FunctionParams)->ProtectionEnabled );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_SetRamBlockStatus
*
* Description: Non-trusted function call for NvM_SetRamBlockStatus
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_SetRamBlockStatus(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtSetRamBlockStatusRec*)FunctionParams)->BlockId].StdRtn = NvM_SetRamBlockStatus( ((NtSetRamBlockStatusRec*)FunctionParams)->BlockId,
                                                                                                            ((NtSetRamBlockStatusRec*)FunctionParams)->BlockChanged );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_SetDataIndex
*
* Description: Non-trusted function call for NvM_SetDataIndex
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_SetDataIndex(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtSetDataIndexRec*)FunctionParams)->BlockId].StdRtn = NvM_SetDataIndex( ((NtSetDataIndexRec*)FunctionParams)->BlockId,
                                                                                                  ((NtSetDataIndexRec*)FunctionParams)->DataIndex );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_GetDataIndex
*
* Description: Non-trusted function call for NvM_GetDataIndex
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_GetDataIndex(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtGetDataIndexRec*)FunctionParams)->BlockId].StdRtn = NvM_GetDataIndex( ((NtGetDataIndexRec*)FunctionParams)->BlockId,
                                                                                                  &Rte_Pim_CmdRtnBuf()[((NtGetDataIndexRec*)FunctionParams)->BlockId].ReqRes );

    return;
}

/**********************************************************************************************************************
* Name:        NONTRUSTED_NtWrapS_NvM_WriteBlock
*
* Description: Non-trusted function call for NvM_WriteBlock
*
* Inputs:      FunctionIndex - Non-trusted function index
*              FunctionParams - Pointer to parameter structure 
*
* Outputs:      None
*
* Usage Notes: 
**********************************************************************************************************************/
FUNC(void, CDD_NvMProxy_CODE) NONTRUSTED_NtWrapS_NvM_WriteBlock(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams)
{
    Rte_Pim_CmdRtnBuf()[((NtWriteBlockRec*)FunctionParams)->BlockId].StdRtn = NvM_WriteBlock( ((NtWriteBlockRec*)FunctionParams)->BlockId,
                                                                                              ((NtWriteBlockRec*)FunctionParams)->NvM_SrcPtr );

    return;
}
#define CDD_NvMProxy_STOP_SEC_CODE
#include "CDD_NvMProxy_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */
